const OPENINGS = [{ sub:"Repertorio con negras: Clásica 4...Bf5",
 id:"caro-kann", name:"Defensa Caro-Kann", short:"Caro-Kann", side:"b", first:"1.e4 c6",
 intro:"Contra 1.e4, las negras preparan ...d5 apoyado por el peón de c6. Es una defensa sólida: estructura de peones sana y, a diferencia de la Francesa, el alfil de casillas blancas sale antes de cerrar la cadena con ...e6.",
 groups:[
  {id:"clasica", name:"Clásica (3.Nc3 / 3.Nd2)", desc:"Blancas mantienen la tensión central y las negras cambian en e4 para sacar el alfil a f5."},
  {id:"karpov", name:"Karpov (4...Nd7)", desc:"Elección: en lugar de 4...Bf5, el caballo va a d7 para retomar con caballo en f6 sin doblar peones."},
  {id:"avance", name:"Avance (3.e5)", desc:"Blancas ganan espacio. Las negras sacan el alfil fuera de la cadena y atacan la base con ...c5."},
  {id:"panov", name:"Panov-Botvinnik (4.c4)", desc:"Blancas aceptan un peón aislado en d4 a cambio de actividad."},
  {id:"cambio", name:"Cambio (3.exd5 cxd5)", desc:"Estructura simétrica. Blancas juegan con Bd3, Nf3 o Nc3; negras presionan d4 y hacen el ataque de minorías ...b5-b4."},
  {id:"otras", name:"Sistemas alternativos", desc:"Respuestas de blancas que evitan 2.d4."}
 ],
 choices:[
  {id:"cuarta", at:"e4 c6 d4 d5 Nc3 dxe4 Nxe4", title:"Cuarta jugada en la Clásica", desc:"Después de 3.Nc3 (o 3.Nd2) dxe4 4.Nxe4: las dos respuestas más jugadas por los maestros.",
   options:[{move:"Bf5", name:"Clásica", desc:"El alfil sale activo antes de ...e6. Estructura sólida y planes claros.", def:true},
            {move:"Nd7", name:"Karpov", desc:"Prepara ...Ngf6 para retomar con caballo si blancas cambian. Muy sólida, pero hay que conocer las trampas en e6 y f7."}]},
  {id:"av3", at:"e4 c6 d4 d5 e5", title:"Contra el Avance", desc:"Después de 3.e5 blancas ganan espacio. Dos maneras de responder.",
   options:[{move:"Bf5", name:"Principal", desc:"La más jugada: el alfil sale antes de cerrar la cadena con ...e6.", def:true},
            {move:"c5", name:"Botvinnik-Carls", desc:"Golpe inmediato contra d4. Menos teoría y juego activo; Stockfish la ve un poco peor que 3...Bf5."}]}
 ],
 lines:[
  {id:"cl-main", group:"clasica", name:"Principal: 6.h4 h6 7.Nf3",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 Nd7 h5 Bh7 Bd3 Bxd3 Qxd3 e6 Bd2 Ngf6 O-O-O Be7 Kb1 O-O",
   notes:{1:"La jugada que define la Caro-Kann: prepara ...d5 sin encerrar el alfil de c8.",3:"Golpe central. El peón de e4 queda atacado.",4:"Defiende e4 con pieza. Contra 3.Nd2 el plan es idéntico.",5:"Cambiamos en e4: soltamos el centro, pero ganamos tiempo y abrimos la diagonal del alfil.",7:"La Clásica. El alfil sale activo antes de ...e6 y ataca al caballo.",8:"El caballo se retira ganando tiempo sobre el alfil.",9:"Único buen retiro que mantiene el alfil en la diagonal b1-h7.",10:"Blancas amenazan h5 para atrapar el alfil.",11:"Casilla de escape en h7. No temas el peón en h6: más adelante sirve de refugio.",13:"El caballo de d7 controla e5 y evita Ne5, que presionaría g6/f7.",14:"Blancas ganan espacio en el flanco de rey, pero el peón de h5 puede volverse un blanco.",15:"El alfil se refugia. Sigue mirando la diagonal hacia b1.",17:"Cambiamos alfiles: menos piezas, menos ataque para blancas.",19:"Ahora sí ...e6: el alfil ya está fuera de la cadena.",21:"Desarrollo natural. f6 defiende h7 y controla e4.",22:"Enroque largo típico: blancas planean atacar con g4-g5 o jugar en el centro.",23:"Desarrollo modesto pero sólido. Mantiene opciones de enroque a ambos lados.",25:"Enroque corto. El plan es ...c5 o ...Qc7 y ...c5 para contraatacar en el centro."},
   plan:"Estructura: blancas tienen más espacio (d4, h5). Negras son sólidas y sin debilidades. Planes: ...c5 para atacar d4, ...Qc7/...Qa5 y, si blancas se enrocan largo, contraataque en el flanco de dama con ...b5 o ...c5. Ojo con la casilla e5: la controla el Nd7."},
  {id:"cl-nd2", group:"clasica", name:"Con 3.Nd2 (transpone)",
   moves:"e4 c6 d4 d5 Nd2 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 Nd7 h5 Bh7 Bd3 Bxd3 Qxd3 e6",
   notes:{4:"3.Nd2 evita la variante 3.Nc3 con ...b5 y otras. Para nosotros no cambia nada.",5:"Mismo cambio que contra 3.Nc3.",7:"Llegamos a la misma posición que la línea principal."},
   plan:"Misma estructura que la principal. Si conocés la Clásica con 3.Nc3, contra 3.Nd2 jugás exactamente igual."},
  {id:"cl-nf3", group:"clasica", name:"6.Nf3 sin h4",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 Nf3 Nd7 Bd3 Bxd3 Qxd3 e6 O-O Ngf6 c4 Be7",
   notes:{10:"Sin h4, el alfil de g6 no está en peligro. Blancas juegan un desarrollo tranquilo.",11:"El mismo esquema: controlamos e5.",13:"Cambiamos el alfil de todas formas: el de d3 apuntaba a nuestro enroque.",19:"Enroque corto después, y el plan típico es ...c5 o ...Qc7 con ...e5."},
   plan:"Posición tranquila. Negras completan desarrollo con ...O-O, ...Qc7 y buscan liberar con ...c5 o ...e5. Sin h5 blanco, el peón de h7 no hace falta mover."},
  {id:"cl-bc4", group:"clasica", name:"6.Bc4",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 Bc4 e6 N1e2 Nf6 h4 h6 Nf4 Bh7 O-O Bd6",
   notes:{10:"El alfil presiona e6 y f7.",11:"Cerramos la diagonal hacia f7. Con el alfil de c8 afuera, ...e6 no tiene costo.",12:"El caballo va a f4 para saltar sobre g6.",14:"De nuevo h4-h5 como amenaza al alfil.",15:"Preparamos el retiro a h7.",17:"El alfil se aparta del caballo de f4.",19:"Desarrollo activo: el alfil de d6 discute el caballo de f4."},
   plan:"Negras se desarrollan con ...Nbd7, ...Qc7 y enroque. El cambio en f4 (...Bxf4) es habitual para quitar el caballo más peligroso."},
  {id:"av-short", group:"avance", name:"Short: 4.Nf3 e6 5.Be2",
   moves:"e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 Be3 Nd7 O-O Ne7 c3 Nc6 Nbd2 Be7",
   notes:{4:"3.e5: blancas ganan espacio y cierran el centro.",5:"El alfil sale ANTES de ...e6. Esta es la ventaja sobre la Francesa.",7:"Ahora sí cerramos con ...e6.",9:"Atacamos la base de la cadena (d4). Es el plan central de las negras en el Avance.",11:"El caballo de d7 presiona e5 y apoya ...c5.",13:"Ruta Ne7-c6 para sumar presión sobre d4.",15:"Tercera pieza apuntando a d4.",17:"Desarrollo y luego enroque corto."},
   plan:"Presión sobre d4 con ...c5, ...Nc6, ...Qb6. Blancas intentan mantener el centro. Si blancas cambian en c5, recuperamos con el alfil o el caballo con buen juego. Evitá abrir el flanco de rey innecesariamente."},
  {id:"av-h4", group:"avance", name:"Tal: 4.h4",
   moves:"e4 c6 d4 d5 e5 Bf5 h4 h5 Bd3 Bxd3 Qxd3 e6 Bg5 Qa5+ c3 Qa6 Qxa6 Nxa6",
   notes:{6:"Blancas amenazan g4 atrapando el alfil.",7:"Frenamos el avance del peón de h. La casilla g5 queda débil, pero g4 deja de ser posible.",9:"Cambiamos: el alfil de d3 era el mejor de blancas.",13:"Truco típico: jaque que obliga a c3 y prepara el cambio de damas.",15:"Ofrecemos cambiar damas: sin damas, la ventaja de espacio blanca pesa menos.",17:"El caballo en a6 va a c7 o b4 si hace falta."},
   plan:"Final cómodo para negras: ...c5 para atacar el centro, ...Nc7 y ...Ne7-f5. La debilidad de g5/h4 de blancas compensa la de g6/h5."},
  {id:"av-nc3", group:"avance", name:"4.Nc3 e6 5.g4",
   moves:"e4 c6 d4 d5 e5 Bf5 Nc3 e6 g4 Bg6 Nge2 c5 h4 h5 Nf4 Bh7 Nxh5 Nc6 dxc5 Bxc5",
   notes:{8:"Variante agresiva: blancas corren con peones contra el alfil.",9:"El alfil se retira sin perder la diagonal.",11:"Contraataque central inmediato: es la respuesta correcta a los avances en el flanco.",13:"Frenamos h5, que atraparía el alfil.",15:"El alfil queda en h7. Posición muy teórica: más adelante vale la pena revisarla con motor.",17:"Desarrollo con presión sobre d4 y e5.",19:"Recuperamos el peón con el alfil activo apuntando a f2."},
   plan:"Línea filosa. Negras deben contraatacar rápido con ...Nc6, ...cxd4 y ...Nge7. No te quedes pasivo: si blancas completan g4-h4-Nf4 sin respuesta central, el ataque es peligroso."},
  {id:"av-bd3", group:"avance", name:"4.Bd3",
   moves:"e4 c6 d4 d5 e5 Bf5 Bd3 Bxd3 Qxd3 e6 Nf3 Qb6 O-O c5",
   notes:{6:"Blancas ofrecen cambiar su mejor alfil. Es inofensivo.",7:"Cambiamos con gusto: nuestro alfil malo por su alfil bueno.",11:"La dama presiona d4 y b2.",13:"Golpe estándar contra la cadena."},
   plan:"Negras están muy cómodas: sin alfiles de casillas blancas, la estructura de la Francesa sin su problema principal. Plan: ...Nc6, ...cxd4, ...Nge7-f5."},
  {id:"pn-main", group:"panov", name:"Principal: 5...e6",
   moves:"e4 c6 d4 d5 exd5 cxd5 c4 Nf6 Nc3 e6 Nf3 Be7 cxd5 Nxd5 Bd3 Nc6 O-O O-O Re1 Bf6 Be4 Nce7",
   notes:{4:"Cambio en d5.",5:"Retomamos con el peón de c.",6:"Panov: blancas atacan d5 y aceptan peón aislado en d4.",7:"Presionamos d5 y desarrollamos.",9:"Estructura sólida: vamos a bloquear el peón aislado.",11:"Desarrollo antes de enrocar.",13:"El caballo en d5 es el bloqueador ideal del peón aislado.",15:"Presión sobre d4.",19:"El alfil presiona d4 desde f6.",21:"Reforzamos d5: el caballo de e7 apoya al de d5."},
   plan:"Juego contra el peón aislado: bloquear en d5, cambiar piezas menores y presionar d4. Cada cambio favorece a negras. Blancas buscan ataque con Ne5, Bc2 y Qd3 contra h7."},
  {id:"cm-main", group:"cambio", name:"Principal: 4.Bd3",
   moves:"e4 c6 d4 d5 exd5 cxd5 Bd3 Nc6 c3 Nf6 Bf4 Bg4 Qb3 Qd7 Nd2 e6 Ngf3 Bd6 Bxd6 Qxd6 O-O O-O",
   notes:{6:"Variante del Cambio: blancas se desarrollan sin tensión.",7:"Presión sobre d4.",11:"El alfil sale activo antes de ...e6.",12:"Blancas atacan b7.",13:"Defendemos b7 y conectamos.",15:"Cerramos la cadena ahora que el alfil ya salió.",17:"Ofrecemos cambio de alfiles.",21:"Posición equilibrada."},
   plan:"Ataque de minorías: ...b5-b4 para crear una debilidad en c3. Blancas juegan en el flanco de rey con Ne5 y f4. Estructura muy segura para negras."},
  {id:"ot-2n", group:"otras", name:"Dos Caballos: 2.Nc3 d5 3.Nf3",
   moves:"e4 c6 Nc3 d5 Nf3 Bg4 h3 Bxf3 Qxf3 e6 d3 Nf6 Bd2 Nbd7 g4 Bb4 g5 Ng8 h4 d4",
   notes:{2:"Blancas evitan 2.d4.",3:"Igual que siempre: ...d5.",5:"Clavada: el alfil sale y presiona el caballo que defiende e4.",7:"Cedemos la pareja de alfiles a cambio de estructura y desarrollo.",9:"Sólido: e6 y d5 frenan a la dama y al alfil.",15:"Clavamos el caballo de c3 y presionamos e4.",17:"El caballo vuelve; más adelante sale por e7.",19:"Ganamos espacio en el centro con tiempo sobre el caballo de c3."},
   plan:"Negras juegan ...d4 o ...dxe4 según convenga, ...Qc7 y enroque. Blancas tienen la pareja de alfiles pero sin centro."},
  {id:"ot-fant", group:"otras", name:"Fantasía: 3.f3",
   moves:"e4 c6 d4 d5 f3 e6 Nc3 Bb4 Bd2 Ne7 a3 Bxc3 Bxc3 b6",
   notes:{4:"Blancas sostienen e4 con peón.",5:"Sólido: preparamos ...c5 o ...dxe4 según convenga.",7:"Clavada sobre el caballo que defiende e4.",9:"El caballo va a g6 o f5, nunca a f6 (lo molestaría e5).",11:"Cambiamos: blancas pierden un defensor de e4.",13:"Preparamos ...Ba6 para cambiar el alfil de casillas blancas."},
   plan:"Presión sobre e4 y el centro con ...dxe4 o ...c5. El peón de f3 debilita el flanco de rey blanco y la diagonal g1-a7."},
  {id:"ot-c4", group:"otras", name:"2.c4",
   moves:"e4 c6 c4 d5 exd5 cxd5 cxd5 Nf6 Nc3 Nxd5 Nf3 Nc6 Bb5 e6 O-O Be7 d4 O-O Re1 Bd7",
   notes:{2:"Blancas atacan d5 antes de que se arme.",3:"Igual jugamos ...d5.",7:"No retomamos con la dama: ...Nf6 recupera el peón con desarrollo.",9:"Peón recuperado.",11:"Presión sobre d4.",17:"Suele transponer a estructuras de la Panov.",19:"Desarrollo tranquilo; después ...Rc8 y presión en la columna c."},
   plan:"Estructura de peón aislado blanco, como en la Panov. Mismo plan: bloquear en d5 y presionar d4."},
  {id:"ot-kia", group:"otras", name:"Indio de Rey: 2.d3",
   moves:"e4 c6 d3 d5 Nd2 e5 Ngf3 Bd6 g3 Nf6 Bg2 O-O O-O Re8 Re1 Nbd7 c3 a5 a4 Nc5",
   notes:{2:"Sistema cerrado. Blancas evitan teoría.",5:"Tomamos el centro con los dos peones.",7:"El alfil apoya e5.",13:"La torre refuerza e5.",15:"El caballo va a c5 pasando por d7.",17:"Frena b4 y gana espacio en el flanco de dama.",19:"El caballo presiona d3 y e4."},
   plan:"Negras tienen un centro amplio. Planes: ...a5-a4 para ganar espacio en el flanco de dama, ...Nbd7 y ...Bc7. Blancas buscan f4 o c3-d4."},
  {id:"ot-bc4", group:"otras", name:"2.Bc4",
   moves:"e4 c6 Bc4 d5 exd5 cxd5 Bb5+ Bd7 Bxd7+ Nxd7 d4 Ngf6",
   notes:{2:"Blancas desarrollan el alfil donde ...d5 lo ataca.",3:"Directamente ...d5 con tiempo.",7:"Cubrimos el jaque ofreciendo cambio.",9:"Retomamos con desarrollo.",11:"Negras están cómodas: buen centro y desarrollo fácil."},
   plan:"Posición cómoda: ...e6, ...Bd6 y enroque. Negras no tienen problemas."},
  {id:"cl-bc4-oo", group:"clasica", name:"6.Bc4 con 8.O-O y f4",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 Bc4 e6 N1e2 Nf6 O-O Bd6 f4 Bf5 Nxf5 exf5",
   notes:{14:"Blancas enrocan y preparan f4-f5 para atrapar al alfil de g6.",15:"El alfil sale a d6 para vigilar f4.",16:"Amenaza f5.",17:"El alfil vuelve a f5 a tiempo. Después del cambio, el peón de f5 controla e4."},
   plan:"Negras quedan sólidas con el peón de f5 frenando a blancas. Enroque corto, ...Nbd7 y ...Qc7 o ...c5 para presionar el centro."},
  {id:"cl-nh3", group:"clasica", name:"6.Nh3",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 Nh3 e6 Nf4 Bd6 c3 Nf6 h4 Bxf4 Bxf4 h6",
   notes:{10:"El caballo va a f4 para cambiar el alfil de g6 o apoyar h4-h5.",13:"El alfil sale a d6 para cambiar el caballo de f4.",17:"Cambiamos el caballo antes de que salte sobre g6: quedamos con estructura sana.",19:"Le damos una casilla al alfil por si blancas juegan h5."},
   plan:"Negras juegan ...Nbd7, ...Qc7 y enroque. El alfil de g6 sigue siendo su mejor pieza y no hay debilidades."},
  {id:"cl-nf3-re1", group:"clasica", name:"6.Nf3 con 10.Re1",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 Nf3 Nd7 Bd3 Bxd3 Qxd3 e6 O-O Ngf6 Re1 Be7",
   notes:{18:"La torre se pone frente al rey negro: prepara golpes en e6 si negras se descuidan.",19:"Desarrollo tranquilo; después enroque corto y ...c5 o ...Qc7."},
   plan:"Como con 10.c4: enroque, ...Qc7 y ...c5 o ...e5 para liberar. Mientras el rey siga en el centro, ojo con los sacrificios en e6."},
  {id:"cl-bd3", group:"clasica", name:"5.Bd3?! Qxd4: el peón de regalo",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Bd3 Qxd4 Nf3 Qd8 O-O Bxe4 Bxe4 Qxd1 Rxd1 Nf6 Bd3 e6",
   notes:{8:"Un error común en niveles de club: deja el peón de d4 sin defensa.",9:"Ganamos un peón. Stockfish da ventaja a negras.",11:"La dama vuelve a casa antes de que la persigan.",13:"Cambiamos el caballo fuerte de e4.",15:"Cambiar damas apaga el ataque blanco: nos quedamos con un peón de más en el final."},
   plan:"Negras tienen un peón de más y ninguna debilidad. Desarrollo con ...Nbd7, ...Be7 y enroque; en el final, el peón extra del flanco de dama decide."},
  {id:"ka-ng5", group:"karpov", name:"Principal: 5.Ng5",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7 Ng5 Ngf6 Bd3 e6 N1f3 Bd6 Qe2 h6 Ne4 Nxe4 Qxe4 Qc7",
   notes:{7:"La Karpov: el caballo prepara ...Ngf6 para que, si blancas cambian en f6, retomemos con caballo sin doblar peones.",8:"El salto más agresivo, apuntando a f7 y e6.",9:"Ahora sí sale el otro caballo.",11:"Necesario. Ojo: acá ...h6?? pierde por Nxe6 (así cayó Kasparov contra Deep Blue en 1997). Primero ...Bd6 y ...Qe7 o ...Qc7.",15:"Con e6 bien cubierto, ahora sí echamos al caballo.",19:"La dama vigila e5 y prepara ...b6, ...Bb7 y ...c5."},
   plan:"Negras juegan ...b6, ...Bb7 y ...c5 o ...e5 para liberar. Estructura sólida y sin debilidades: la idea de Karpov es neutralizar y jugar el medio juego con calma."},
  {id:"ka-bc4", group:"karpov", name:"5.Bc4 Ngf6 6.Ng5",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7 Bc4 Ngf6 Ng5 e6 Qe2 Nb6 Bd3 h6 N5f3 c5 dxc5 Bxc5",
   notes:{8:"El alfil apunta a f7.",10:"Amenaza Nxf7.",11:"Cubre f7 y e6.",12:"Prepara sacrificios en e6 y f7: todavía no se puede ...h6.",13:"Echa al alfil de c4 antes de jugar ...h6.",15:"Con el alfil lejos de c4, ahora sí echamos al caballo.",17:"El golpe liberador típico de la Karpov."},
   plan:"Negras completan con ...Qc7, ...Bd7 y enroque. Los caballos blancos ya no tienen buenas casillas y la ruptura ...c5 abrió el juego."},
  {id:"ka-bb3", group:"karpov", name:"5.Bc4 Ngf6 6.Ng5 con 8.Bb3",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7 Bc4 Ngf6 Ng5 e6 Qe2 Nb6 Bb3 h6 N5f3 a5 a3 a4",
   notes:{14:"El alfil se queda en la diagonal a2-g8.",15:"Ya sin peligro en e6, echamos al caballo.",17:"Amenaza ...a4 atrapando al alfil.",19:"El alfil tiene que irse de b3."},
   plan:"Negras ganaron espacio en el flanco de dama. Siguen con ...c5 y ...Bd6, y el alfil blanco queda pasivo."},
  {id:"ka-bc4-x", group:"karpov", name:"5.Bc4 Ngf6 6.Nxf6+",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7 Bc4 Ngf6 Nxf6+ Nxf6 c3 Qc7 Qb3 e6 Nf3 Bd6 O-O O-O",
   notes:{10:"Blancas cambian: justamente por esto jugamos ...Nd7, para retomar con caballo.",11:"Estructura sana, sin peones doblados.",13:"La dama vigila e5 y f4.",15:"Cubre f7 frente a la dama y el alfil.",17:"Alfil activo en d6, apuntando al rey."},
   plan:"Negras completan con ...b6, ...Bb7 y ...c5. Posición sólida y equilibrada."},
  {id:"ka-ng3", group:"karpov", name:"5.Nf3 Ngf6 6.Ng3",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7 Nf3 Ngf6 Ng3 e6 Bd3 c5 O-O cxd4 Nxd4 Bc5 Nb3 Be7",
   notes:{8:"Desarrollo tranquilo.",10:"Evita el cambio y deja el caballo cerca del flanco de rey.",13:"La ruptura típica contra d4.",15:"Cambiamos y abrimos la columna c.",17:"Gana tiempo atacando al caballo."},
   plan:"Negras enrocan corto y juegan ...b6 y ...Bb7: el alfil en la gran diagonal compensa el espacio blanco."},
  {id:"ka-ne5", group:"karpov", name:"5.Nf3 Ngf6 6.Nxf6+ Nxf6 7.Ne5",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7 Nf3 Ngf6 Nxf6+ Nxf6 Ne5 Be6 Be2 g6 O-O Bg7 c4 O-O",
   notes:{12:"El caballo se instala en e5.",13:"El alfil sale a e6 y vigila d5 y c4.",15:"Fianchetto: el alfil en g7 presiona d4 y e5."},
   plan:"Negras juegan ...Nd7 o ...Qc7 para cambiar el caballo de e5. Posición segura con el alfil de g7 muy activo."},
  {id:"ka-bd3", group:"karpov", name:"5.Nf3 Ngf6 6.Bd3",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7 Nf3 Ngf6 Bd3 Nxe4 Bxe4 Nf6 Bd3 Bg4 c3 e6 h3 Bh5",
   notes:{11:"Cambiamos el caballo activo de e4.",13:"El otro caballo vuelve a f6 ganando tiempo sobre el alfil.",15:"El alfil sale antes de ...e6, como en la Clásica."},
   plan:"Negras completan con ...Bd6 o ...Be7, ...Qc7 y enroque. Sin debilidades y con el alfil fuera de la cadena."},
  {id:"ka-nf3-bc4", group:"karpov", name:"5.Nf3 Ngf6 6.Nxf6+ Nxf6 7.Bc4",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7 Nf3 Ngf6 Nxf6+ Nxf6 Bc4 Bf5 O-O e6 c3 Bd6 Bg5 Qc7",
   notes:{12:"Desarrollo natural apuntando a f7.",13:"Con el caballo en f6, el alfil sale cómodo a f5.",19:"La dama conecta las torres y vigila e5."},
   plan:"Estructura como en la Clásica, sin el tiempo perdido con el alfil. Enroque y ...Nd5 o ...Rad8."},
  {id:"ka-qe2", group:"karpov", name:"5.Qe2: la trampa del mate ahogado",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7 Qe2 Ndf6 Nf3 Nxe4 Qxe4 Nf6 Qd3 g6 Be2 Bg7 O-O O-O",
   notes:{8:"Una trampa conocida: si 5...Ngf6??, 6.Nd6# es mate ahogado.",9:"Sale este caballo: ahora d6 queda cubierto por el peón de e7.",15:"Fianchetto: el alfil presiona d4."},
   plan:"Negras juegan ...Bf5 o ...Bg4, ...Qc7 y ...c5 o ...e5. Posición cómoda."},
  {id:"av-short-c4", group:"avance", name:"Short con 8.c4",
   moves:"e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 Be3 Nd7 O-O Ne7 c4 dxc4 Na3 Nd5 Nxc4 Be7",
   notes:{14:"Blancas atacan d5 para abrir el juego.",15:"Tomamos: el peón de c4 no se puede sostener.",16:"El caballo va a recuperar el peón.",17:"El caballo se instala en d5, una casilla ideal.",19:"Desarrollo y enroque."},
   plan:"Negras tienen un caballo excelente en d5 y presionan d4 con ...cxd4 o ...Nc6. Enroque corto y ...Qb6 o ...Rc8."},
  {id:"av-short-bg5", group:"avance", name:"Short con 8.c4 y 10.Bg5",
   moves:"e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 Be3 Nd7 O-O Ne7 c4 dxc4 Na3 Nd5 Bg5 Be7",
   notes:{18:"El alfil ataca a la dama de d8.",19:"Interponemos y ofrecemos cambiar alfiles."},
   plan:"Negras recuperan comodidad con ...O-O y ...Nxc4 o ...Qb6. El caballo de d5 sigue siendo la mejor pieza."},
  {id:"av-short-oo", group:"avance", name:"Short con 6.O-O",
   moves:"e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 O-O Nc6 c3 Bg6 a3 cxd4 cxd4 Nge7 Nc3 Nf5",
   notes:{10:"Enroque antes de Be3.",11:"Presión directa sobre d4.",13:"El alfil se retira a g6 por si blancas juegan Nh4.",15:"Cambiamos para abrir la columna c.",17:"El caballo va a f5 a presionar d4."},
   plan:"Negras atacan d4 con ...Nf5, ...Qb6 y ...Be7. Si d4 cae, negras quedan mejor."},
  {id:"av-short-c4b", group:"avance", name:"Short con 7.c4",
   moves:"e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 Be3 Nd7 c4 dxc4 Bxc4 Ne7 Nc3 Nc6 O-O Be7",
   notes:{12:"Ataca d5 de inmediato.",13:"Tomamos y el alfil tiene que recuperar.",15:"El caballo va a c6 o f5 para presionar d4.",17:"Más presión sobre d4."},
   plan:"Como en la principal: presión sobre d4 con ...cxd4, ...Qb6 y enroque corto."},
  {id:"av-nf3-bd3", group:"avance", name:"Short con 5.Bd3",
   moves:"e4 c6 d4 d5 e5 Bf5 Nf3 e6 Bd3 Bxd3 Qxd3 Qb6 O-O c5 c3 Qa6 Qxa6 Nxa6 Be3 Rc8",
   notes:{8:"Blancas ofrecen cambiar alfiles.",9:"Cambiamos: sin su alfil de casillas blancas, blancas controlan menos d3 y c4.",15:"Ofrecemos cambiar damas: el final es cómodo para negras."},
   plan:"Final sin damas con presión en la columna c. Negras ya no tienen alfil malo: el de casillas blancas se cambió."},
  {id:"av-nd2", group:"avance", name:"4.Nd2",
   moves:"e4 c6 d4 d5 e5 Bf5 Nd2 e6 Nb3 Nd7 Nf3 h6 Be2 Ne7 O-O g5 a4 Bg7 a5 Qc7",
   notes:{6:"Prepara Nb3 para controlar c5 y frenar ...c5.",9:"Prepara ...c5 de todas formas, o ...Ne7.",11:"Deja h7 para el alfil y prepara ...g5.",15:"Espacio en el flanco de rey: ...Bg7 va a presionar e5."},
   plan:"Negras atacan e5 con ...Bg7 y ...f6, y juegan ...c5 cuando puedan. El rey puede quedarse en el centro o irse al flanco de dama."},
  {id:"av-g4", group:"avance", name:"4.g4",
   moves:"e4 c6 d4 d5 e5 Bf5 g4 Be4 f3 Bg6 h4 h5 e6 Qd6 exf7+ Bxf7 Ne2 hxg4 fxg4 Nd7",
   notes:{6:"Ataque directo al alfil.",7:"El alfil se va a e4 y provoca f3, que debilita al rey blanco.",9:"Vuelve a g6.",11:"Frenamos el avance del peón h.",12:"Sacrificio de peón para abrir líneas.",13:"La dama vigila e6, g3 y h2.",15:"Recuperamos el peón: el alfil queda bien en f7."},
   plan:"El flanco de rey blanco quedó muy debilitado. Negras juegan ...e6 o ...e5, ...Ngf6 y enroque largo."},
  {id:"av-f4", group:"avance", name:"4.f4",
   moves:"e4 c6 d4 d5 e5 Bf5 f4 e6 Nf3 c5 c3 Nc6 Bb5 Qb6 Bxc6+ bxc6 O-O h5 Kh1 Nh6",
   notes:{6:"Refuerza e5 pero encierra al alfil de c1.",9:"La ruptura de siempre contra d4.",11:"Presión sobre d4.",13:"La dama ataca d4 y b2.",19:"El caballo va a f5, una casilla ideal."},
   plan:"El alfil blanco de c1 quedó encerrado. Negras juegan ...Nf5, ...Be7 y ...cxd4 para presionar el centro."},
  {id:"av-nf3-nc3", group:"avance", name:"Short con 5.Nc3",
   moves:"e4 c6 d4 d5 e5 Bf5 Nf3 e6 Nc3 Nd7 Bd3 Bxd3 Qxd3 Ne7 Bg5 h6 Bh4 Qb6 b3 Nf5",
   notes:{8:"Desarrollo; frena ...c5 por un momento.",11:"Cambiamos alfiles.",15:"Preguntamos al alfil.",17:"Presión sobre d4 y b2.",19:"El caballo ataca d4 y al alfil de h4."},
   plan:"Negras presionan d4 con ...c5 y ...Qb6. El caballo de f5 es muy fuerte."},
  {id:"av-h4-nd2", group:"avance", name:"Tal con 8.Nd2",
   moves:"e4 c6 d4 d5 e5 Bf5 h4 h5 Bd3 Bxd3 Qxd3 e6 Bg5 Qa5+ Nd2 c5 c4 dxc4 Qxc4 Nc6",
   notes:{14:"Cubre el jaque con el caballo.",15:"Ataca d4 enseguida.",17:"Tomamos: la dama blanca recupera, pero pierde tiempo.",19:"Desarrollo con presión sobre d4 y e5."},
   plan:"Negras atacan el centro con ...cxd4 y ...Nge7-f5. El peón de h4 dejó débil la casilla g4."},
  {id:"av-h4-c4", group:"avance", name:"Tal con 5.c4",
   moves:"e4 c6 d4 d5 e5 Bf5 h4 h5 c4 e6 Nc3 Ne7 Nge2 Nd7 Ng3 Bg6 Bg5 Qb6 Rc1 Qxb2",
   notes:{8:"Blancas atacan d5.",9:"Sostenemos d5.",11:"El caballo defiende d5 y puede ir a f5 o g6.",15:"El alfil se retira antes de que el caballo de g3 lo cambie.",17:"La dama ataca b2 y d4.",19:"Ganamos un peón."},
   plan:"Negras ganaron un peón. Hay que completar el desarrollo con cuidado: la dama vuelve a b6 o a6 y después enroque largo."},
  {id:"avc-nf3", group:"avance", name:"3...c5 4.Nf3",
   moves:"e4 c6 d4 d5 e5 c5 Nf3 cxd4 Nxd4 Nc6 Nxc6 bxc6 Bd3 e6 O-O Ne7 Nd2 a5 Nf3 Ba6",
   notes:{5:"Golpe inmediato contra d4, antes de sacar el alfil. El peón de c juega dos veces, pero blancas ya se comprometieron con e5.",7:"Cambiamos en d4.",9:"Desarrollo con ataque al caballo.",11:"Retomamos hacia el centro: el peón de c6 apoya ...c5 más adelante.",19:"Cambiamos el alfil bueno de blancas."},
   plan:"Negras juegan ...c5 y ...Nf5 o ...Ng6 para presionar e5. Peones centrales móviles."},
  {id:"avc-be3", group:"avance", name:"3...c5 4.dxc5 e6 5.Be3",
   moves:"e4 c6 d4 d5 e5 c5 dxc5 e6 Be3 Nd7 Bb5 Ne7 Bd4 Nc6 Bxc6 bxc6 b4 a5 a3 Ba6",
   notes:{6:"Blancas toman e intentan sostener el peón de más.",7:"Abrimos el alfil para recuperar c5.",9:"Ataca e5 y c5.",11:"El caballo va a c6 o f5.",17:"Atacamos la cadena de peones.",19:"El alfil se activa en la diagonal a6-f1."},
   plan:"Negras recuperan el peón de c5 o rompen la cadena con ...axb4. Juego activo en el flanco de dama."},
  {id:"avc-a3", group:"avance", name:"3...c5 4.dxc5 e6 5.a3",
   moves:"e4 c6 d4 d5 e5 c5 dxc5 e6 a3 Bxc5 Nf3 f6 b4 Be7 Bb2 a5 b5 Nd7 c4 Nxe5",
   notes:{9:"Recuperamos el peón.",11:"Atacamos la base de la cadena: e5.",15:"Atacamos el peón de b4.",19:"Ganamos el peón de e5."},
   plan:"Negras tienen buen centro. Completan con ...Ngf6 o ...Nxf3+ y enroque."},
  {id:"avc-qg4", group:"avance", name:"3...c5 4.dxc5 e6 5.a3 Bxc5 6.Qg4",
   moves:"e4 c6 d4 d5 e5 c5 dxc5 e6 a3 Bxc5 Qg4 Ne7 Nf3 O-O Bd3 f5 exf6 Rxf6 Qh5 h6",
   notes:{10:"La dama ataca g7.",11:"Desarrollo, preparando el enroque.",13:"El rey se va a un lugar seguro.",15:"Rompemos la cadena.",17:"La torre se activa en la columna f."},
   plan:"Negras quedan con buen centro y la columna f abierta: ...Nbc6, ...e5 y ...Bd7."},
  {id:"avc-b4", group:"avance", name:"3...c5 4.dxc5 e6 5.a3 Bxc5 6.b4",
   moves:"e4 c6 d4 d5 e5 c5 dxc5 e6 a3 Bxc5 b4 Be7 Nf3 a5 b5 Nd7 c4 dxc4 Bxc4 b6",
   notes:{10:"Gana espacio con tiempo.",13:"Atacamos la cadena.",15:"El caballo ataca e5.",19:"Preparamos ...Bb7 y ...Nc5."},
   plan:"Negras juegan ...Bb7, ...Nc5 y ...Ne7: presión contra e5 y buenas casillas en c5."},
  {id:"avc-nf3b", group:"avance", name:"3...c5 4.dxc5 e6 5.Nf3",
   moves:"e4 c6 d4 d5 e5 c5 dxc5 e6 Nf3 Bxc5 Bd3 Nc6 O-O Nge7 a3 Ng6 b4 Bb6 Bb2 O-O",
   notes:{9:"Recuperamos el peón.",11:"Ataca e5.",15:"Más presión sobre e5.",17:"El alfil apunta a f2."},
   plan:"Negras atacan e5 con ...f6 o ...Qc7 y tienen buen juego en el centro."},
  {id:"avc-qxd4", group:"avance", name:"3...c5 4.Nf3 cxd4 5.Qxd4",
   moves:"e4 c6 d4 d5 e5 c5 Nf3 cxd4 Qxd4 Nc6 Qf4 e6 Bd3 Nb4 Nc3 Nxd3+ cxd3 Ne7 h4 h5",
   notes:{9:"Desarrollo ganando tiempo sobre la dama.",13:"Va por el alfil de d3.",15:"Nos quedamos con el par de alfiles.",17:"El caballo va a g6 o f5."},
   plan:"Negras tienen el par de alfiles y la estructura más sana: ...Ng6 o ...Nf5, ...Be7 y enroque."},
  {id:"avc-c3", group:"avance", name:"3...c5 4.c3",
   moves:"e4 c6 d4 d5 e5 c5 c3 Nc6 Nf3 cxd4 cxd4 Bg4 Be2 e6 O-O Nge7 Nc3 Nf5 Be3 Be7",
   notes:{6:"Sostiene d4 con un peón, como en la Francesa.",7:"Presión sobre d4.",11:"El alfil clava al caballo que defiende d4.",17:"Más presión sobre d4."},
   plan:"Estructura de Francesa Avance pero con el alfil de c8 afuera. Negras presionan d4 con ...Qb6 y ...Nf5."},
  {id:"avc-c3-bb5", group:"avance", name:"3...c5 4.c3 Nc6 5.Bb5",
   moves:"e4 c6 d4 d5 e5 c5 c3 Nc6 Bb5 cxd4 cxd4 Bf5 Nc3 e6 Nge2 Ne7 O-O a6 Ba4 b5",
   notes:{8:"Clava el caballo.",11:"El alfil sale antes de ...e6.",17:"Preguntamos al alfil.",19:"Ganamos espacio y lo echamos."},
   plan:"Negras juegan ...Nc8-b6 o ...Ng6 y presionan con ...Qb6. El alfil blanco quedó lejos, en a4."},
  {id:"pn-nf3", group:"panov", name:"Panov por 4.Nf3 Nc6 5.c4",
   moves:"e4 c6 d4 d5 exd5 cxd5 Nf3 Nc6 c4 Nf6 Nc3 Bg4 cxd5 Nxd5 Qb3 Bxf3 gxf3 e6 Qxb7 Nxd4",
   notes:{8:"Transpone a una Panov.",11:"Presión sobre d4: clavamos al caballo que lo defiende.",15:"Cambiamos y debilitamos el enroque blanco.",17:"Defendemos y abrimos el alfil de f8.",19:"Contragolpe: si blancas tomaron en b7, nosotros ganamos d4."},
   plan:"Posición muy táctica: negras tienen piezas activas y el rey blanco debilitado. ...Bc5 o ...Bb4 y enroque."},
  {id:"cm-nf3", group:"cambio", name:"4.Nf3 Nc6 5.Bd3",
   moves:"e4 c6 d4 d5 exd5 cxd5 Nf3 Nc6 Bd3 Bg4 c3 e6 O-O Bd6 h3 Bh5 Be3 Nge7 Nbd2 Rc8",
   notes:{6:"Desarrollo antes de decidir entre c4 y Bd3.",7:"Presión sobre d4.",9:"El alfil sale y clava al caballo.",13:"Alfil activo apuntando a h2.",17:"El caballo va a g6 o f5.",19:"La torre a la columna abierta: se viene el ataque de minorías ...b5-b4."},
   plan:"Negras hacen el ataque de minorías: ...a6, ...b5 y ...b4 para debilitar c3. El alfil de h5 puede volver a g6."},
  {id:"cm-nf3-c3", group:"cambio", name:"4.Nf3 Nc6 5.c3",
   moves:"e4 c6 d4 d5 exd5 cxd5 Nf3 Nc6 c3 Nf6 Bd3 Bg4 O-O e6 Bg5 Bd6 Nbd2 Qc7 h3 Bh5",
   notes:{8:"Sostiene d4 con peón.",11:"El alfil sale antes de ...e6.",17:"La dama vigila h2 y la columna c."},
   plan:"Como en el Cambio con Bd3: ataque de minorías ...b5-b4 y buenas casillas para los caballos en e4 y c4."},
  {id:"cm-nf3-bb5", group:"cambio", name:"4.Nf3 Nc6 5.Bb5",
   moves:"e4 c6 d4 d5 exd5 cxd5 Nf3 Nc6 Bb5 e6 O-O Bd6 Nc3 Ne7 Bg5 f6 Bh4 O-O Re1 a6",
   notes:{8:"Clava el caballo.",13:"El caballo de e7 refuerza c6.",15:"Echamos al alfil.",19:"Preguntamos al otro alfil."},
   plan:"Negras juegan ...Bd7 y ...Qc7, con buen centro y el par de alfiles si blancas cambian en c6."},
  {id:"cm-nf3-nc3", group:"cambio", name:"4.Nf3 Nc6 5.Nc3",
   moves:"e4 c6 d4 d5 exd5 cxd5 Nf3 Nc6 Nc3 Bg4 Be2 e6 O-O Nf6 h3 Bh5 Bg5 Bd6 Nb5 Bb8",
   notes:{9:"Clavada sobre el defensor de d4.",17:"El alfil sale a d6.",19:"El alfil se retira sin dejarse cambiar."},
   plan:"Negras juegan ...a6 para echar al caballo, ...O-O y ...Qd6: presión sobre h2 y d4."},
  {id:"cm-nc3", group:"cambio", name:"4.Nc3",
   moves:"e4 c6 d4 d5 exd5 cxd5 Nc3 Nf6 Nf3 Nc6 Bb5 Bg4 h3 Bxf3 Qxf3 e6 Bg5 Be7 O-O O-O",
   notes:{6:"Presiona d5.",7:"Defiende d5.",11:"Clava al caballo.",13:"Cambiamos para debilitar d4.",15:"Abrimos el alfil."},
   plan:"Negras presionan d4 con ...Qb6 y ...Rc8. El peón de d5 está bien sostenido."},
  {id:"cm-h3", group:"cambio", name:"4.Bd3 Nc6 5.c3 Nf6 6.h3",
   moves:"e4 c6 d4 d5 exd5 cxd5 Bd3 Nc6 c3 Nf6 h3 g6 Nf3 Bf5 O-O Bxd3 Qxd3 e6 Re1 Bg7",
   notes:{10:"Evita ...Bg4.",11:"Prepara ...Bf5 y el fianchetto.",13:"El alfil sale igual, a f5.",15:"Cambiamos el alfil bueno de blancas."},
   plan:"Negras juegan ...O-O, ...Ne4 y ...Rc8 con el ataque de minorías ...b5-b4. El alfil de g7 vigila e5."},
  {id:"ot-2n-be2", group:"otras", name:"Dos Caballos con 6.Be2",
   moves:"e4 c6 Nc3 d5 Nf3 Bg4 h3 Bxf3 Qxf3 e6 Be2 Nf6 O-O Nbd7 d4 dxe4 Nxe4 Nxe4 Qxe4 Nf6",
   notes:{10:"Blancas renuncian a d3 y preparan d4.",15:"Cambiamos en e4.",19:"El caballo vuelve a f6 ganando tiempo sobre la dama."},
   plan:"Negras juegan ...Be7, ...O-O y ...Qc7 o ...c5. Sin el caballo de f3, a blancas les cuesta atacar."},
  {id:"ot-2n-d4", group:"otras", name:"Dos Caballos con 6.d4",
   moves:"e4 c6 Nc3 d5 Nf3 Bg4 h3 Bxf3 Qxf3 e6 d4 Nf6 e5 Nfd7 Ne2 c5 c3 Nc6 Be3 Qb6",
   notes:{10:"Centro clásico.",12:"Gana espacio: queda una estructura de Francesa.",15:"Atacamos la base de la cadena.",19:"Presión sobre b2 y d4."},
   plan:"Estructura de Francesa en la que negras ya cambiaron su alfil malo: presión con ...c5, ...Nc6 y ...Qb6 sobre d4."},
  {id:"ot-qf3", group:"otras", name:"2.Qf3",
   moves:"e4 c6 Qf3 d5 exd5 cxd5 c4 d4 c5 Nc6 Bc4 Nf6 d3 Bg4 Qg3 e6 Bg5 Bf5",
   notes:{2:"Salida prematura de la dama, común en niveles bajos.",3:"Ocupamos el centro igual.",7:"Ganamos espacio con tiempo.",13:"Atacamos a la dama.",17:"El alfil ataca d3."},
   plan:"Negras tienen mejor centro y desarrollo: ...Be7, ...O-O y ...Qa5 o ...Nd7 para atacar c5."},
  {id:"ot-qh5", group:"otras", name:"2.Qh5",
   moves:"e4 c6 Qh5 d5 exd5 cxd5 Bb5+ Nc6 Bxc6+ bxc6 Nf3 Nh6",
   notes:{2:"Otra salida temprana de la dama.",3:"El centro primero: la dama blanca no amenaza nada serio.",7:"Cubrimos el jaque desarrollando.",9:"Retomamos hacia el centro.",11:"El caballo va a f5 y deja libre al alfil de f8."},
   plan:"Negras tienen el centro y el par de alfiles: ...e6, ...Bd6 y enroque. La dama blanca va a tener que moverse otra vez."},
  {id:"ot-nf3-e5", group:"otras", name:"2.Nf3 d5 3.e5",
   moves:"e4 c6 Nf3 d5 e5 Bg4 d4 e6 h3 Bxf3 Qxf3 c5 c3 Nc6 Bb5 Qb6 Bxc6+ bxc6 O-O cxd4",
   notes:{2:"Evita 2.d4 por ahora.",4:"Gana espacio, como en el Avance.",5:"Con el caballo en f3, el alfil sale a g4 para cambiarlo.",9:"Cambiamos: blancas pierden un defensor de d4.",11:"Atacamos d4.",19:"Abrimos la columna c."},
   plan:"Estructura de Avance donde negras ya cambiaron su alfil: ...Ne7-f5, ...Qa6 y presión sobre el centro."},
  {id:"ot-nf3-be2", group:"otras", name:"2.Nf3 d5 3.e5 Bg4 4.d4 e6 5.Be2",
   moves:"e4 c6 Nf3 d5 e5 Bg4 d4 e6 Be2 c5 c3 Nc6 O-O Nge7 h3 Bxf3 Bxf3 cxd4 cxd4 Qb6",
   notes:{8:"Blancas evitan el cambio de alfil por ahora.",9:"Atacamos d4.",13:"El caballo va a f5.",15:"Cambiamos antes de que nos echen el alfil.",19:"Presión sobre d4 y b2."},
   plan:"Negras atacan d4 con ...Nf5 y ...Qb6. El alfil de f3 choca contra d5."},
  {id:"ot-nf3-d3", group:"otras", name:"2.Nf3 d5 3.d3",
   moves:"e4 c6 Nf3 d5 d3 dxe4 dxe4 Qxd1+ Kxd1 Nf6 Nc3 Bg4 Be2 Nbd7 h3 Bxf3 Bxf3 O-O-O Ke2 e5",
   notes:{4:"Sistema cerrado, tipo Indio de Rey invertido.",5:"Cambiamos en e4.",7:"Cambiamos damas: blancas pierden el enroque.",11:"Presión sobre e4.",17:"El rey se va al flanco de dama y la torre a la columna d."},
   plan:"Final cómodo: negras tienen la columna d y el rey blanco quedó en el centro."},
  {id:"ot-bc4-bb3", group:"otras", name:"2.Bc4 d5 3.exd5 cxd5 4.Bb3",
   moves:"e4 c6 Bc4 d5 exd5 cxd5 Bb3 Nf6 d4 Nc6 Nf3 Bg4 h3 Bxf3 Qxf3 Nxd4 Qd3 Nxb3 Qxb3 Qc7",
   notes:{6:"El alfil se queda en la diagonal.",9:"Presión sobre d4.",13:"Cambiamos al defensor de d4.",15:"Ganamos el peón de d4.",17:"Cambiamos el alfil."},
   plan:"Negras ganaron un peón central. ...e6, ...Bd6 y enroque para consolidar."},
  {id:"ot-bc4-nf3", group:"otras", name:"2.Bc4 d5 3.exd5 cxd5 4.Bb3 Nf6 5.Nf3",
   moves:"e4 c6 Bc4 d5 exd5 cxd5 Bb3 Nf6 Nf3 Nc6 O-O Bg4 h3 Bh5 d3 e6 Bg5 Bd6 Nbd2 h6",
   notes:{8:"Desarrollo sin d4.",11:"Clavada.",15:"Abrimos el alfil.",19:"Preguntamos al alfil."},
   plan:"Negras tienen el centro con d5 y juego cómodo: enroque y ...Qc7 o ...Rc8."},
  {id:"ot-bc4-6nf3", group:"otras", name:"2.Bc4 ... 5.Bxd7+ Nxd7 6.Nf3",
   moves:"e4 c6 Bc4 d5 exd5 cxd5 Bb5+ Bd7 Bxd7+ Nxd7 Nf3 Ngf6 O-O e6 d4 Bd6 Bg5 O-O Nc3 h6",
   notes:{10:"Desarrollo antes de d4.",13:"Abrimos el alfil.",15:"Alfil activo.",19:"Preguntamos al alfil."},
   plan:"Como con 6.d4: negras tienen buen centro y juegan ...Qb6 o ...Rc8 con presión en la columna c."},
  {id:"ot-fant-a3", group:"otras", name:"Fantasía con 5.a3",
   moves:"e4 c6 d4 d5 f3 e6 Nc3 Bb4 a3 Bxc3+ bxc3 dxe4 Qe2 c5 Qxe4 Nf6 Qh4 Nc6",
   notes:{8:"Pregunta al alfil.",9:"Cambiamos y dejamos peones doblados.",11:"Tomamos en e4.",13:"Atacamos d4.",15:"Desarrollo con tiempo sobre la dama.",17:"Más presión sobre d4."},
   plan:"Blancas tienen peones doblados en c. Negras juegan ...Qa5, ...O-O y ...cxd4 para atacar la estructura."}
 ]},
{id:"viena", name:"Viena", side:"w", first:"1.e4 e5 2.Nc3", sub:"Repertorio con blancas: gambito 3.f4 y 3.Bc4",
 intro:"Con 2.Nc3 las blancas controlan d5 y preparan f4 sin exponer el rey de entrada. Contra 2...Nf6 jugamos el gambito 3.f4; contra 2...Nc6, el alfil a c4 con la idea Qg4 si negras juegan ...Bc5.",
 groups:[
  {id:"gambito", name:"Gambito de Viena (2...Nf6 3.f4)", desc:"Abrimos la columna f para atacar. Negras eligen entre el contragolpe ...d5, aceptar o jugar sólido."},
  {id:"bc4", name:"3.Bc4 contra 2...Nc6", desc:"El alfil apunta a f7. Contra ...Bc5 aparece la jugada 4.Qg4, con amenazas dobles."},
  {id:"otras", name:"Otras segundas de negras", desc:"Para que no te saquen de la preparación en la jugada 2."}
 ],
 lines:[
  {id:"vg-d5", group:"gambito", name:"3...d5 (principal)",
   moves:"e4 e5 Nc3 Nf6 f4 d5 fxe5 Nxe4 Nf3 Be7 d4 O-O Bd3 f5 exf6 Bxf6 O-O Nc6",
   notes:{2:"2.Nc3: controla d5 y deja libre el peón de f para avanzar.",4:"El gambito: atacamos e5 y abrimos la columna f.",5:"La respuesta más fuerte: contragolpe central.",6:"Ganamos espacio con tiempo sobre el caballo de f6.",8:"Desarrollo natural. El peón de e5 queda defendido.",10:"Centro de peones sólido.",12:"El alfil apunta al enroque y presiona el caballo de e4.",14:"Cambiamos para abrir la columna f contra el rey negro.",16:"Enroque con la torre ya en la columna semiabierta."},
   plan:"Blancas tienen presión en la columna f y buen centro. Planes: Ne2/Nxe4 para eliminar el caballo central, Qe1-h4 o Qe2, Bf4/Bg5 y torres en la columna f."},
  {id:"vg-exf4", group:"gambito", name:"3...exf4 (acepta)",
   moves:"e4 e5 Nc3 Nf6 f4 exf4 e5 Ng8 Nf3 d6 d4 dxe5 Qe2 Be7 dxe5",
   notes:{5:"Negras aceptan el peón.",6:"Clave: echamos el caballo antes de que juegue ...d5.",7:"El único retiro seguro.",8:"Evita ...Qh4+ y desarrolla.",10:"Centro fuerte. El peón de f4 lo vamos a recuperar con Bxf4.",12:"La dama defiende e5 por la columna e y prepara Bxf4 y enroque largo.",14:"Retomamos y mantenemos el peón central."},
   plan:"Blancas recuperan el peón con Bxf4, enrocan largo y juegan con ventaja de desarrollo y espacio. El peón de e5 es una cuña en la posición negra."},
  {id:"vg-exf4-qe7", group:"gambito", name:"3...exf4 4.e5 Qe7",
   moves:"e4 e5 Nc3 Nf6 f4 exf4 e5 Qe7 Qe2 Ng8 Nf3 d6 exd6 Qxe2+ Bxe2 cxd6 Nd5",
   notes:{7:"Clavada sobre e5: la dama negra ataca el peón.",8:"Defendemos e5 con la dama y rompemos la clavada.",12:"Cambiamos y abrimos el juego.",14:"Retomamos con el alfil: desarrollo con tiempo.",16:"El caballo salta a d5 atacando c7 y f4."},
   plan:"Final cómodo para blancas: recuperamos el peón de f4 y tenemos más actividad. Nd5, Bxf4 y enroque."},
  {id:"vg-d6", group:"gambito", name:"3...d6 (sólido)",
   moves:"e4 e5 Nc3 Nf6 f4 d6 Nf3 Nc6 Bb5 Bd7 O-O",
   notes:{5:"Negras sostienen e5 sin tomar riesgos.",6:"Desarrollo con presión sobre e5.",8:"Clavada sobre el caballo que defiende e5.",10:"Enroque. Amenaza fxe5 abriendo la columna f."},
   plan:"Blancas buscan d3, Qe1-g3 o Kh1 y fxe5 en el momento justo. La columna f es la vía de ataque."},
  {id:"vg-nc6", group:"gambito", name:"3...Nc6",
   moves:"e4 e5 Nc3 Nf6 f4 Nc6 fxe5 Nxe5 d4 Ng6 e5 Ng8 Nf3",
   notes:{5:"Negras desarrollan y dejan que blancas tomen en e5.",6:"Tomamos: el caballo negro queda expuesto.",8:"Echamos el caballo con tiempo.",10:"Seguimos ganando tiempos.",12:"Centro enorme y desarrollo muy superior."},
   plan:"Ventaja clara de espacio. Bd3 o Bc4, enroque y ataque en el flanco de rey."},
  {id:"bc-bc5", group:"bc4", name:"3...Bc5 4.Qg4",
   moves:"e4 e5 Nc3 Nc6 Bc4 Bc5 Qg4 Qf6 Nd5 Qxf2+ Kd1 Kf8 Nh3 Qd4 d3",
   notes:{4:"El alfil apunta a f7.",5:"Negras copian el esquema.",6:"Ataca g7. Si negras no lo cubren bien, Qxg7 gana la torre de h8. Además la dama y el alfil apuntan juntos a f7.",7:"La defensa más natural: protege g7 y amenaza f2.",8:"Atacamos la dama y c7.",9:"Negras toman con jaque, pero la dama queda lejos de su rey.",10:"El rey se mueve. Parece arriesgado pero la dama negra va a quedar sola.",12:"Defendemos y preparamos Rf1 contra f7.",14:"Encerramos el juego de la dama negra y preparamos Rf1."},
   plan:"Negras ganaron un peón pero su rey no se puede enrocar y la dama está expuesta. Blancas siguen con Rf1, Qxg7 si se permite y c3 para echar la dama."},
  {id:"bc-bc5-g6", group:"bc4", name:"3...Bc5 4.Qg4 g6",
   moves:"e4 e5 Nc3 Nc6 Bc4 Bc5 Qg4 g6 Qf3 Nf6 Nge2 d6 d3",
   notes:{7:"Negras defienden g7 con peón, pero debilitan f6 y h6.",8:"La dama vuelve a presionar f7.",9:"Tapa la diagonal hacia f7.",10:"Desarrollo sin bloquear el peón de f.",12:"Esquema sólido: preparamos Bg5 y f4."},
   plan:"Las casillas oscuras del flanco de rey negro quedaron debilitadas. Blancas juegan Bg5, h4-h5 o f4 según la posición."},
  {id:"bc-nf6", group:"bc4", name:"3...Nf6",
   moves:"e4 e5 Nc3 Nc6 Bc4 Nf6 d3 Bc5 f4 d6 Nf3",
   notes:{5:"Negras desarrollan y amenazan ...Nxe4.",6:"Defendemos e4 con peón. Preparamos f4.",8:"Ahora sí f4: estructura de gambito del rey rehusado con el alfil en c4.",10:"Desarrollo. Si negras cambian en f4, Bxf4 con juego activo."},
   plan:"Blancas enrocan corto y juegan con la columna f. Ojo con ...Ng4 contra f2: el enroque lo neutraliza. Si negras juegan ...Na5, retirar el alfil a b3."},
  {id:"ot-bc5", group:"otras", name:"2...Bc5",
   moves:"e4 e5 Nc3 Bc5 Nf3 d6 d4 exd4 Nxd4 Nf6 Bg5",
   notes:{3:"Negras sacan el alfil antes que los caballos.",4:"Desarrollo con ataque a e5.",6:"Golpe central con tiempo sobre el alfil.",8:"Centralizamos el caballo.",10:"Clavada sobre f6: presión y desarrollo."},
   plan:"Blancas tienen más centro. Qd2 y enroque largo es un plan agresivo; también Be2 y enroque corto."},
  {id:"ot-d6", group:"otras", name:"2...d6",
   moves:"e4 e5 Nc3 d6 Nf3 Nf6 d4 Nbd7 Bc4 Be7 O-O O-O",
   notes:{3:"Negras juegan pasivo.",4:"Desarrollo con presión a e5.",6:"Transpone a una Philidor favorable para blancas.",8:"El alfil en c4 presiona f7.",10:"Enroque y a desarrollar el juego central."},
   plan:"Ventaja de espacio. Planes: a4 para frenar ...b5, Re1, h3 y Be3. Negras están sólidas pero apretadas."}
 ]},
{id:"holandesa", name:"Holandesa Leningrado", short:"Holandesa", cover:8, side:"b", first:"1...f5 contra 1.d4, 1.c4, 1.Nf3 y 1.g3", sub:"Repertorio con negras: Leningrado",
 intro:"Con 1...f5 las negras controlan e4 y buscan juego de ataque en el flanco de rey. En la Leningrado el alfil va a g7, como en la India de Rey, y el plan típico es ...d6, ...Qe8 y ...e5.",
 groups:[
  {id:"principal", name:"Principal (1.d4 f5 2.g3)", desc:"El esquema fiancheto de blancas. Es la posición central del repertorio."},
  {id:"transp", name:"Otras primeras jugadas", desc:"1.c4, 1.Nf3 y 1.g3 llegan a la misma estructura."},
  {id:"anti", name:"Anti-Holandesas", desc:"Blancas evitan la estructura con jugadas tempranas contra f5."}
 ],
 lines:[
  {id:"ln-main", group:"principal", name:"Principal con 7.Nc3 Qe8",
   moves:"d4 f5 g3 Nf6 Bg2 g6 Nf3 Bg7 O-O O-O c4 d6 Nc3 Qe8 d5 a5 Nd4 Na6 e4 fxe4 Nxe4 Nxe4 Bxe4 Nc5",
   notes:{1:"1...f5: controlamos e4 y desequilibramos desde la primera jugada.",3:"Desarrollo y control de e4.",5:"Fiancheto: el alfil de g7 va a ser la pieza clave de la defensa.",7:"El alfil cubre el rey y presiona la gran diagonal.",9:"Enroque rápido. En la Holandesa el rey negro necesita estar seguro antes de abrir.",11:"Controlamos e5 y preparamos ...e5.",13:"La jugada típica de la Leningrado: la dama va a h5 o f7 y apoya ...e5.",15:"Ganamos espacio en el flanco de dama y aseguramos c5 para un caballo.",17:"El caballo va a c5 por a6.",19:"Abrimos la columna f para las torres.",21:"Simplificamos el centro.",23:"El caballo llega a c5, casilla fuerte asegurada por ...a5."},
   plan:"Negras tienen juego en las casillas oscuras (c5, e5) y en la columna f. Planes: ...Bd7, ...Qf7 presionando c4 y f2, ...c6 para abrir el flanco de dama. El alfil de g7 no se cambia."},
  {id:"ln-c4", group:"principal", name:"Con 2.c4",
   moves:"d4 f5 c4 Nf6 Nc3 g6 Nf3 Bg7 g3 O-O Bg2 d6 O-O Qe8",
   notes:{3:"El mismo esquema, sin importar el orden de blancas.",9:"Enroque antes de ...d6.",13:"Llegamos a la posición principal."},
   plan:"Transpone a la línea principal. Seguí el mismo plan: ...a5, ...Na6 y ...e5 o ...c6."},
  {id:"tr-c4", group:"transp", name:"1.c4 f5",
   moves:"c4 f5 g3 Nf6 Bg2 g6 Nc3 Bg7 Nf3 O-O O-O d6 d4 Qe8",
   notes:{1:"Contra la Inglesa también jugamos 1...f5.",3:"Mismo esquema.",11:"Si blancas no juegan d4, igual seguimos con ...Qe8 y ...e5.",13:"Transpone a la principal."},
   plan:"Si blancas mantienen el peón en d3 en lugar de d4, el plan ...e5 es todavía más fuerte porque tenemos más centro."},
  {id:"tr-nf3", group:"transp", name:"1.Nf3 f5",
   moves:"Nf3 f5 g3 Nf6 Bg2 g6 O-O Bg7 c4 O-O Nc3 d6 d4 Qe8",
   notes:{1:"Contra 1.Nf3 el mismo movimiento.",3:"Nada cambia.",13:"Transpone de nuevo a la principal."},
   plan:"Misma estructura que la principal. Si blancas juegan d3 y e4, respondemos con ...e5 y ...Nc6."},
  {id:"tr-g3", group:"transp", name:"1.g3 f5",
   moves:"g3 f5 Bg2 Nf6 Nf3 g6 O-O Bg7 c4 O-O d4 d6 Nc3 Qe8",
   notes:{1:"Contra 1.g3, mismo esquema.",13:"Transpone a la principal."},
   plan:"Mismo plan que la principal."},
  {id:"an-staunton", group:"anti", name:"Gambito Staunton 2.e4",
   moves:"d4 f5 e4 fxe4 Nc3 Nf6 Bg5 g6 f3 exf3 Nxf3 Bg7 Bd3 O-O O-O d6",
   notes:{2:"Blancas ofrecen un peón para abrir el juego.",3:"Aceptamos: si no, blancas toman en f5 con buen juego.",5:"Defendemos el peón de e4.",7:"Mantenemos el esquema Leningrado.",9:"Tomamos otro peón. El caballo de f3 pierde tiempo.",11:"El alfil defiende el enroque.",13:"Rey seguro antes de todo.",15:"Controlamos e5 y consolidamos el peón de ventaja."},
   plan:"Negras tienen un peón de ventaja. Blancas buscan ataque con Qe1-h4 y Bh6. Plan negro: ...Nc6, ...Bg4 y cambiar piezas para capitalizar el peón."},
  {id:"an-staunton-f3", group:"anti", name:"Staunton con 4.f3",
   moves:"d4 f5 e4 fxe4 Nc3 Nf6 f3 exf3 Nxf3 g6 Bd3 Bg7 O-O O-O",
   notes:{6:"Blancas buscan abrir la columna f de inmediato.",7:"Tomamos y quedamos con peón de ventaja.",9:"Seguimos con el esquema.",13:"Rey seguro."},
   plan:"Igual que el Staunton con Bg5: consolidar con ...d6, ...Nc6 y ...Bg4."},
  {id:"an-bg5", group:"anti", name:"2.Bg5",
   moves:"d4 f5 Bg5 h6 Bh4 g5 Bg3 Nf6 e3 d6 h4 g4",
   notes:{2:"Blancas atacan e7 y amenazan cambiar el caballo antes de que salga.",3:"Preguntamos al alfil.",5:"Lo echamos del flanco de rey.",7:"Recién ahora el caballo.",9:"Controlamos e5.",11:"Cerramos el flanco: el alfil de g3 queda con poco juego."},
   plan:"Negras ganaron espacio en el flanco de rey. Planes: ...Bg7, ...Nc6 y ...e5. Cuidado con la casilla e6 y la diagonal h5-e8."},
  {id:"an-nc3", group:"anti", name:"2.Nc3",
   moves:"d4 f5 Nc3 Nf6 Bg5 d5 Bxf6 exf6 e3 c6 Bd3 g6 Nge2 Bd6",
   notes:{2:"Blancas preparan e4.",5:"Frenamos e4 con peón.",7:"Retomamos hacia el centro: la columna e queda abierta.",9:"Cadena sólida.",11:"Fiancheto no hace falta: el alfil va a d6.",13:"El alfil controla e5 y f4."},
   plan:"Estructura tipo Stonewall con la pareja de alfiles para negras. Plan: ...O-O, ...Nd7-f8, ...Qc7. El peón de e5 es una ruptura para blancas a vigilar."}
 ]},
{id:"italiana", name:"Apertura Italiana", short:"Italiana", level:"basico", side:"w", first:"1.e4 e5 2.Nf3 Nc6 3.Bc4", sub:"Para empezar con blancas: Giuoco Pianissimo",
 intro:"La apertura más clásica para aprender: peón al centro, caballo que ataca e5 y alfil apuntando a f7. Elegimos la versión tranquila, con c3 y d3: casi no tiene teoría, los planes son claros (enroque, Re1, Nbd2-f1-g3 y d4) y la estructura es la misma contra casi todo. Si las negras no contestan 1...e5, aplicá los principios: centro, desarrollo y enroque.",
 groups:[
  {id:"piano", name:"Giuoco Piano (3...Bc5)", desc:"La respuesta más natural: las negras copian y sacan el alfil a c5."},
  {id:"doscab", name:"Dos Caballos (3...Nf6)", desc:"Las negras atacan e4. Lo defendemos con d3 y seguimos con el mismo plan."},
  {id:"otras", name:"Otras defensas", desc:"Respuestas menos comunes, con alguna trampa que conviene conocer."}
 ],
 lines:[
  {id:"it-piano", group:"piano", name:"Principal: 4.c3 Nf6 5.d3",
   moves:"e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Bb3 Ba7 Nbd2",
   notes:{0:"Ocupamos el centro y abrimos camino a la dama y al alfil.",2:"Desarrollo con ataque: el caballo ataca el peón de e5.",4:"El alfil apunta a f7, la casilla más débil de las negras: solo la defiende el rey.",6:"Preparamos d4 para ganar el centro más adelante.",8:"La versión tranquila (Giuoco Pianissimo): defendemos e4 y no damos ventajas.",10:"El rey a salvo antes de abrir el juego.",12:"La torre apoya e4 y, más adelante, el avance d4.",14:"Retiramos el alfil antes de que ...Na5 o ...b5 lo cambien o lo echen.",16:"El caballo va a f1 y después a g3: la maniobra típica de la Italiana."},
   plan:"Maniobra Nbd2-f1-g3, h3 para evitar ...Bg4 y, cuando todo esté listo, d3-d4 para abrir el centro con las piezas bien puestas. Si las negras se descuidan, Bg5 clava el caballo de f6."},
  {id:"it-2c", group:"doscab", name:"4.d3 Be7",
   moves:"e4 e5 Nf3 Nc6 Bc4 Nf6 d3 Be7 O-O O-O Re1 d6 c3",
   notes:{5:"Defensa de los Dos Caballos: las negras atacan e4.",6:"Defendemos e4 con un peón. 4.Ng5 es más agresivo, pero muy táctico.",8:"Enroque primero, como siempre.",10:"La torre apoya e4.",12:"Mismo esquema que en el Giuoco: c3 y después d4."},
   plan:"Igual que en la Italiana principal: Bb3, Nbd2-f1-g3, h3 y d4. Las negras están sólidas, pero tenemos más espacio y un plan simple."},
  {id:"it-2c-bc5", group:"doscab", name:"4.d3 Bc5 (transpone)",
   moves:"e4 e5 Nf3 Nc6 Bc4 Nf6 d3 Bc5 c3 d6 O-O O-O",
   notes:{7:"El alfil a c5 nos lleva a la línea principal por otro orden.",8:"Igual que siempre: c3 para preparar d4."},
   plan:"Es la misma posición que el Giuoco Pianissimo: seguí con Re1, Bb3 y Nbd2-f1-g3."},
  {id:"it-be7", group:"otras", name:"Húngara: 3...Be7",
   moves:"e4 e5 Nf3 Nc6 Bc4 Be7 d3 Nf6 O-O O-O",
   notes:{5:"Defensa Húngara: sólida pero pasiva. El alfil no apunta a ningún lado.",6:"No hace falta forzar: d3 y desarrollo.",7:"Transponemos a los Dos Caballos con ...Be7."},
   plan:"El mismo plan de siempre: Re1, c3, Bb3, Nbd2-f1-g3 y d4. Con el alfil negro en e7, f7 sigue siendo un blanco."},
  {id:"it-nd4", group:"otras", name:"Trampa: 3...Nd4",
   moves:"e4 e5 Nf3 Nc6 Bc4 Nd4 Nxd4 exd4 c3",
   notes:{5:"¡Trampa! Si 4.Nxe5?, viene ...Qg5 atacando e5 y g2, y si 5.Nxf7?? Qxg2 6.Rf1 Qxe4+ 7.Be2 Nf3#. No tomes en e5.",6:"Lo simple: cambiamos el caballo.",8:"Atacamos d4 y seguimos desarrollando. Las negras movieron dos veces el mismo caballo: estamos mejor."},
   plan:"Desarrollo normal con d3 o d4, Nc3 y enroque. Las negras perdieron tiempo; usalo para ocupar el centro."},
  {id:"it-philidor", group:"otras", name:"Philidor: 2...d6",
   moves:"e4 e5 Nf3 d6 d4 exd4 Nxd4 Nf6 Nc3 Be7 Bc4 O-O O-O",
   notes:{3:"Defensa Philidor: sostiene e5 con un peón, pero encierra el alfil de f8.",4:"Golpeamos el centro enseguida.",6:"Retomamos con pieza: más espacio y desarrollo fácil.",10:"El alfil a su diagonal favorita, apuntando a f7.",12:"Desarrollo completo."},
   plan:"Más espacio para blancas. Ideas: Re1, Bf4 o Bg5, f4 si las negras se quedan pasivas. Las negras buscan ...Re8, ...Bf8 y ...c6."},
  {id:"it-petrov", group:"otras", name:"Petrov: 2...Nf6",
   moves:"e4 e5 Nf3 Nf6 Nxe5 d6 Nf3 Nxe4 d4 d5 Bd3",
   notes:{3:"Defensa Petrov: las negras contraatacan e4 en lugar de defender e5.",4:"Tomamos el peón. Ojo: si las negras copian con 3...Nxe4?, 4.Qe2! les gana material.",5:"Lo correcto: primero echan al caballo.",6:"Retirada segura.",8:"Centro y espacio.",10:"Atacamos el caballo de e4 y preparamos el enroque."},
   plan:"O-O, c4 para atacar d5, Re1 y Nc3 para cambiar el caballo fuerte de e4. Posición simétrica, pero con algo más de iniciativa para blancas."}
 ]},
{id:"abierto", name:"Juego abierto 1...e5", short:"1...e5", level:"basico", side:"b", first:"1.e4 e5", sub:"Para empezar con negras contra 1.e4",
 intro:"Contestar 1.e4 con 1...e5 es la mejor escuela: posiciones abiertas, desarrollo rápido y táctica. El repertorio usa ideas simples: ...Nc6 y ...Bc5 contra la Italiana, la Ruy López Cerrada contra 3.Bb5 y desarrollo con ...Nf6 y ...Bb4 contra la Escocesa. Incluye cómo frenar el ataque del pastor y los gambitos más comunes.",
 groups:[
  {id:"italiana", name:"Italiana (3.Bc4)", desc:"Copiamos con ...Bc5 y reforzamos el centro con ...Nf6 y ...d6."},
  {id:"espanola", name:"Ruy López (3.Bb5)", desc:"El alfil presiona al caballo que defiende e5. Lo preguntamos con ...a6."},
  {id:"escocesa", name:"Escocesa y Cuatro Caballos", desc:"Blancas abren el centro con d4 o sacan los dos caballos."},
  {id:"otras", name:"Otras de blancas", desc:"Pastor, Gambito de Rey, Apertura del Centro y Viena."}
 ],
 lines:[
  {id:"ab-ital", group:"italiana", name:"Giuoco Pianissimo: 4.c3 Nf6 5.d3",
   moves:"e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Bb3 Ba7",
   notes:{1:"Simetría: también reclamamos el centro.",3:"Defendemos e5 desarrollando una pieza.",5:"El alfil activo apunta a f2.",7:"Atacamos e4 y preparamos el enroque.",9:"Sostenemos e5 y abrimos el alfil de c8.",11:"El rey a salvo.",13:"Casilla de retirada para el alfil: si blancas juegan d4, b4 o Na4, ya está a salvo en a7.",15:"El alfil queda en la diagonal a7-g1, apuntando al rey blanco."},
   plan:"Posición equilibrada. Planes: ...Be6 para cambiar el alfil de b3, ...h6 para evitar Bg5 y ...Ne7-g6. Si blancas juegan d4, cambiá en d4 y presioná e4."},
  {id:"ab-ital-d4", group:"italiana", name:"4.c3 Nf6 5.d4",
   moves:"e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d4 exd4 cxd4 Bb4+ Bd2 Bxd2+ Nbxd2 d5 exd5 Nxd5 Qb3 Nce7 O-O O-O",
   notes:{8:"La versión agresiva: blancas arman un centro grande.",9:"Cambiamos: no podemos sostener e5.",11:"Jaque que gana tiempo y nos deja cambiar piezas.",13:"Cambiamos alfiles.",15:"¡La liberación clave! Rompemos el centro antes de que avance e5.",17:"Caballo fuerte en d5.",18:"Blancas atacan d5 y b7.",19:"Defendemos d5 con el otro caballo.",21:"Rey a salvo. A blancas les queda un peón aislado en d4: es un blanco para todo el medio juego."},
   plan:"Bloqueá el peón de d4 (una pieza en d5 es ideal), cambiá piezas y apuntá al peón aislado con ...c6, ...Nf5 y las torres en la columna d."},
  {id:"ab-ital-oo", group:"italiana", name:"4.O-O Nf6 5.d3",
   moves:"e4 e5 Nf3 Nc6 Bc4 Bc5 O-O Nf6 d3 d6 c3 O-O",
   notes:{7:"El mismo esquema que contra 4.c3.",11:"Llegamos a la posición del Giuoco Pianissimo."},
   plan:"Igual que en el Giuoco Pianissimo: ...a6 y ...Ba7, ...h6 y ...Be6."},
  {id:"ab-evans", group:"italiana", name:"Gambito Evans: 4.b4",
   moves:"e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bb6 a4 a6 Nc3 Nf6",
   notes:{6:"Gambito Evans: blancas ofrecen un peón para ganar tiempo con c3 y d4.",7:"Lo declinamos: cero riesgo y el alfil sigue en la diagonal buena.",9:"Si a5, el alfil se retira a a7.",11:"Desarrollo normal."},
   plan:"...d6, ...O-O y ...Bg4. Blancas gastaron jugadas de peón en el flanco de dama: completá el desarrollo y la posición es cómoda."},
  {id:"ab-ruy", group:"espanola", name:"Ruy López Cerrada",
   moves:"e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3",
   notes:{4:"Ruy López (Española): el alfil presiona al caballo que defiende e5.",5:"Le preguntamos al alfil qué quiere hacer.",7:"Atacamos e4.",8:"Blancas no defienden e4: si ...Nxe4, Re1 lo recupera.",9:"Desarrollo tranquilo para enrocar.",10:"Ahora sí blancas amenazan Bxc6 y Nxe5.",11:"Por eso echamos al alfil.",13:"Sostenemos e5.",15:"Rey a salvo: es la Ruy López Cerrada, una de las posiciones más jugadas de la historia.",16:"Evita ...Bg4."},
   plan:"...Na5 para cambiar el alfil de b3, ...c5 para ganar espacio, ...Re8 y ...Bf8. Es una lucha lenta: paciencia y piezas coordinadas."},
  {id:"ab-ruy-cambio", group:"espanola", name:"Cambio: 4.Bxc6",
   moves:"e4 e5 Nf3 Nc6 Bb5 a6 Bxc6 dxc6 O-O f6 d4 exd4 Nxd4 c5 Nb3 Qxd1 Rxd1",
   notes:{6:"Variante del Cambio: blancas nos dejan peones doblados.",7:"Retomamos hacia el centro y se abren líneas para la dama y el alfil. Si ahora 5.Nxe5?, ...Qd4! recupera el peón.",8:"Ahora sí blancas amenazan Nxe5.",9:"Defendemos e5 con un peón.",13:"Echamos al caballo del centro.",15:"Cambio de damas: con la pareja de alfiles, el final es cómodo para negras."},
   plan:"La pareja de alfiles compensa los peones doblados. ...Bd6, ...Ne7, ...Be6 y el rey a f7 o enroque largo. Evitá cambiar los alfiles."},
  {id:"ab-escocesa", group:"escocesa", name:"Escocesa: 4...Nf6 5.Nc3",
   moves:"e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6 Nc3 Bb4 Nxc6 bxc6 Bd3 d5 exd5 cxd5 O-O O-O Bg5 c6",
   notes:{4:"Escocesa: blancas abren el centro enseguida.",5:"Cambiamos: no hay forma cómoda de sostener e5.",7:"Atacamos e4 con desarrollo.",9:"Clavamos el caballo que defiende e4.",11:"Retomamos hacia el centro.",13:"Golpe central: ahora el centro es nuestro.",19:"Sólido: d5 queda bien defendido."},
   plan:"...h6 para echar al alfil, ...Bd6 y ...Re8. El peón de d5 da espacio; la columna b semiabierta sirve para la torre."},
  {id:"ab-escocesa-e5", group:"escocesa", name:"Escocesa: 5.Nxc6 bxc6 6.e5",
   moves:"e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6 Nxc6 bxc6 e5 Qe7 Qe2 Nd5 c4 Nb6",
   notes:{9:"Retomamos hacia el centro.",10:"Echan al caballo.",11:"Atacamos e5 y preparamos ...Nd5.",13:"El caballo se instala en d5.",15:"Retirada segura. Posición compleja pero sana."},
   plan:"...Bb7, ...O-O-O o ...g6 y ...Bg7, y presión sobre e5 con ...d6. Blancas tienen espacio; nosotros, una estructura flexible."},
  {id:"ab-4c", group:"escocesa", name:"Cuatro Caballos: 4.d4",
   moves:"e4 e5 Nf3 Nc6 Nc3 Nf6 d4 exd4 Nxd4 Bb4",
   notes:{4:"Cuatro Caballos: desarrollo simétrico.",6:"Blancas abren el centro.",9:"Llegamos a la Escocesa de Cuatro Caballos."},
   plan:"Seguí como en la Escocesa: ...Bxc3 si hace falta, ...d5 y enroque."},
  {id:"ab-4c-bb5", group:"escocesa", name:"Cuatro Caballos: 4.Bb5",
   moves:"e4 e5 Nf3 Nc6 Nc3 Nf6 Bb5 Bb4 O-O O-O d3 d6",
   notes:{7:"Copiamos: posición simétrica y sólida.",11:"Si blancas clavan con Bg5, podés contestar ...Bxc3 y ...Qe7."},
   plan:"...Bxc3 para doblar peones, ...Qe7 y ...Nd8-e6. Posición tranquila y equilibrada."},
  {id:"ab-4c-bc4", group:"escocesa", name:"Cuatro Caballos: 4.Bc4",
   moves:"e4 e5 Nf3 Nc6 Nc3 Nf6 Bc4 Nxe4 Nxe4 d5 Bd3 dxe4 Bxe4 Bd6",
   notes:{7:"¡El truco de la horquilla! Tomamos e4 aunque parezca que regalamos el caballo.",9:"Horquilla de peón: ataca el alfil y el caballo. Recuperamos la pieza.",13:"Buen centro y desarrollo fácil: las negras están cómodas."},
   plan:"...O-O, ...Re8, ...Nd4 o ...f5 para echar al alfil. El centro de peones e5 y el desarrollo rápido nos dan una partida cómoda."},
  {id:"ab-pastor", group:"otras", name:"Ataque del pastor: 2.Qh5",
   moves:"e4 e5 Qh5 Nc6 Bc4 g6 Qf3 Nf6 Ne2 Bg7 Nbc3 d6 d3 O-O",
   notes:{2:"La dama sale muy temprano: ataca e5 y f7.",3:"Defendemos e5.",4:"Amenaza Qxf7#. ¡Atención!",5:"Tapamos y atacamos la dama.",6:"Otra vez amenaza mate en f7.",7:"Tapamos de nuevo y desarrollamos. Ya tenemos más piezas afuera que las blancas.",9:"Fianchetto: el alfil defiende el enroque.",13:"Desarrollo completo. Blancas perdieron tiempo con la dama."},
   plan:"...Nd4 para atacar la dama y c2, ...Bg4 ganando tiempo y ...Na5 para cambiar el alfil de c4. Estamos mejor desarrollados."},
  {id:"ab-rey", group:"otras", name:"Gambito de Rey: 2.f4",
   moves:"e4 e5 f4 Bc5 Nf3 d6 Nc3 Nf6 Bc4 Nc6 d3 a6",
   notes:{2:"Gambito de Rey: blancas ofrecen un peón para abrir la columna f.",3:"Lo declinamos con el alfil apuntando a g1: el rey blanco no puede enrocar corto. Si 3.fxe5??, ...Qh4+ gana.",5:"Sostenemos e5.",7:"Desarrollo.",9:"Más desarrollo y presión en el centro.",11:"Casilla de retirada para el alfil: Na4 ya no lo cambia."},
   plan:"...Bg4, ...O-O y ...exf4 cuando convenga. El alfil de c5 molesta mucho: blancas no pueden enrocar cómodo."},
  {id:"ab-centro", group:"otras", name:"Apertura del Centro: 2.d4",
   moves:"e4 e5 d4 exd4 Qxd4 Nc6 Qe3 Nf6 Nc3 Bb4 Bd2 O-O O-O-O Re8",
   notes:{3:"Tomamos el peón.",4:"La dama retoma, pero queda expuesta.",5:"¡Desarrollo atacando la dama!",7:"Atacamos e4.",9:"Clavada que suma presión sobre e4.",11:"Rey a salvo.",13:"La torre a la columna abierta: e4 está muy presionado."},
   plan:"Presión sobre e4 con ...Re8, ...d6 y ...Bxc3. Blancas enrocaron largo: ...b5 o ...d5 abren líneas hacia su rey."},
  {id:"ab-viena", group:"otras", name:"Viena: 2.Nc3 Nf6 3.f4",
   moves:"e4 e5 Nc3 Nf6 f4 d5 fxe5 Nxe4 Nf3 Be7 d4 O-O Bd3 f5",
   notes:{2:"Viena: blancas preparan f4.",3:"Desarrollo y presión sobre e4.",5:"El contragolpe central: lo mejor contra el gambito.",7:"Caballo fuerte en e4.",9:"Desarrollo y enroque.",13:"Sostenemos el caballo de e4."},
   plan:"...c5 para atacar el centro, ...Nc6 y ...Be6. El caballo de e4 es nuestra mejor pieza: no lo cambies sin motivo."},
  {id:"ab-viena-bc4", group:"otras", name:"Viena: 3.Bc4",
   moves:"e4 e5 Nc3 Nf6 Bc4 Nc6 d3 Bc5 f4 d6 Nf3",
   notes:{5:"Desarrollo tranquilo.",7:"Copiamos el esquema de la Italiana.",9:"Sostenemos e5 sin miedo a f4."},
   plan:"...Bg4, ...Na5 para cambiar el alfil de c4 y ...O-O. Si fxe5, retomá con el peón de d6."}
 ]},
{id:"gdd", name:"Gambito de Dama Declinado", short:"GDD", level:"basico", side:"b", first:"1.d4 d5 2.c4 e6", sub:"Para empezar con negras contra 1.d4",
 intro:"La defensa clásica contra 1.d4: ...d5, ...e6, ...Nf6, ...Be7 y enroque. Es sólida, con principios clarísimos, y la jugaron todos los campeones del mundo. El único problema es el alfil de c8, encerrado por e6: buena parte del repertorio enseña cómo liberarlo. Contra sistemas sin c4 (Londres, Colle) usamos ...c5.",
 groups:[
  {id:"clasica", name:"Ortodoxa (3.Nc3)", desc:"Blancas clavan con Bg5 o cambian en d5. Ideas de Capablanca para liberar el juego."},
  {id:"nf3", name:"Con Nf3 y Catalana", desc:"Órdenes de jugadas con Nf3 y el fianchetto Catalán con g3."},
  {id:"sistemas", name:"Londres y Colle", desc:"Blancas no juegan c4: armamos el centro con ...c5."}
 ],
 lines:[
  {id:"gd-orto", group:"clasica", name:"Ortodoxa: 4.Bg5",
   moves:"d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3 Nbd7 Rc1 c6 Bd3 dxc4 Bxc4 Nd5 Bxe7 Qxe7 O-O Nxc3 Rxc3 e5",
   notes:{1:"Simetría: peón al centro.",2:"El Gambito de Dama: blancas ofrecen el peón de c4 para desviar el de d5.",3:"Lo declinamos: sostenemos d5 con un peón y abrimos el alfil de f8.",5:"Desarrollo natural.",6:"Clava el caballo contra la dama.",7:"Rompemos la clavada.",9:"El rey a salvo antes que nada.",11:"Desarrollo modesto: el caballo apoya ...c5 o ...e5.",13:"Reforzamos d5 y esperamos a que blancas muevan el alfil.",15:"Ahora que el alfil movió, tomamos en c4: blancas pierden un tiempo.",17:"La maniobra de Capablanca: cambiamos piezas para liberar la posición.",23:"¡La ruptura liberadora! Con ...e5 el alfil de c8 por fin sale."},
   plan:"El gran problema del GDD es el alfil de c8, encerrado por e6. Todo apunta a liberarlo: ...dxc4 en el momento justo, cambios con ...Nd5 y la ruptura ...e5 (o ...c5). Después, ...exd4, ...Nf6 y ...Bg4 o ...Bf5 con juego igualado."},
  {id:"gd-cambio", group:"clasica", name:"Cambio: 4.cxd5",
   moves:"d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 Be7 e3 O-O Bd3 Nbd7 Nf3 c6 Qc2 Re8 O-O Nf8",
   notes:{6:"Variante del Cambio: blancas definen el centro.",7:"Retomamos con el peón de e: se abre el alfil de c8. ¡Problema resuelto!",11:"Enroque.",15:"La estructura de Carlsbad: c6 y d5 sólidos.",17:"La torre a la columna e semiabierta.",19:"El caballo va a g6 o e6 a defender el enroque."},
   plan:"Estructura de Carlsbad. Blancas suelen jugar el ataque de minorías (b4-b5) contra c6. Nosotros: ...Ng6, ...Bd6, ...Ne4 y juego en el flanco de rey. Si llega b5, contestá ...cxb5 o ...c5 con cuidado."},
  {id:"gd-nf3", group:"clasica", name:"4.Nf3 Be7 5.Bg5",
   moves:"d4 d5 c4 e6 Nc3 Nf6 Nf3 Be7 Bg5 O-O e3 Nbd7",
   notes:{7:"El mismo esquema de siempre.",11:"Llegamos a la Ortodoxa."},
   plan:"Seguí como en la Ortodoxa: ...c6, ...dxc4 cuando el alfil de f1 se mueva, ...Nd5 y ...e5."},
  {id:"gd-bf4", group:"clasica", name:"4.Nf3 Be7 5.Bf4",
   moves:"d4 d5 c4 e6 Nc3 Nf6 Nf3 Be7 Bf4 O-O e3 c5 dxc5 Bxc5",
   notes:{8:"El alfil a f4: un sistema moderno y popular.",11:"Golpeamos el centro desde el costado.",13:"Retomamos con el alfil activo."},
   plan:"...Nc6, ...dxc4 en el momento justo y ...Qa5 para presionar c3. El alfil de c8 sale por d7 o b7."},
  {id:"gd-3nf3", group:"nf3", name:"3.Nf3 (transpone)",
   moves:"d4 d5 c4 e6 Nf3 Nf6 Nc3 Be7 Bg5 O-O",
   notes:{4:"Otro orden de jugadas.",7:"Llegamos a las mismas posiciones que con 3.Nc3."},
   plan:"Seguí como en la Ortodoxa: ...Nbd7, ...c6, ...dxc4 y ...Nd5."},
  {id:"gd-nf3-c4", group:"nf3", name:"2.Nf3 Nf6 3.c4",
   moves:"d4 d5 Nf3 Nf6 c4 e6 Nc3 Be7",
   notes:{3:"Desarrollo flexible.",5:"Volvemos al esquema del GDD.",7:"Transpone a la línea con 4.Nf3."},
   plan:"Seguí como en el GDD con 4.Nf3: contra Bg5, ...O-O y ...Nbd7; contra Bf4, ...O-O y ...c5."},
  {id:"gd-catalana", group:"nf3", name:"Catalana: 4.g3",
   moves:"d4 d5 c4 e6 Nf3 Nf6 g3 Be7 Bg2 O-O O-O dxc4 Qc2 a6 Qxc4 b5 Qc2 Bb7",
   notes:{6:"Catalana: el alfil de g2 presionará la diagonal larga.",9:"Enroque.",11:"Tomamos el peón: blancas lo recuperan, pero ganamos tiempo para el flanco de dama.",13:"Preparamos ...b5.",15:"Ganamos espacio atacando la dama.",17:"Nuestro alfil discute la diagonal larga: el problema del alfil de c8 está resuelto."},
   plan:"...Nbd7, ...c5 y ...Rc8. Con el alfil en b7, las negras igualan la lucha por la diagonal larga."},
  {id:"gd-londres", group:"sistemas", name:"Londres: 2.Bf4",
   moves:"d4 d5 Bf4 Nf6 e3 c5 c3 Nc6 Nd2 e6 Ngf3 Bd6 Bg3 O-O Bd3 b6",
   notes:{2:"Sistema Londres: el alfil sale antes de e3.",5:"Contra el Londres, ...c5 es lo más directo.",9:"Ahora sí ...e6, con el esquema del GDD.",11:"Ofrecemos cambiar el alfil más activo de blancas.",15:"Fianchetto: el alfil de c8 sale por b7."},
   plan:"...Bb7, ...Qc7 o ...Qe7 y ...Ne4. La ruptura ...e5 (preparada con ...Qc7) libera el juego."},
  {id:"gd-nf3-bf4", group:"sistemas", name:"Londres: 2.Nf3 y 3.Bf4",
   moves:"d4 d5 Nf3 Nf6 Bf4 c5 e3 Nc6 c3 e6 Nbd2 Bd6 Bg3 O-O Bd3 b6",
   notes:{5:"Mismo plan contra el Londres: ...c5.",9:"El esquema del GDD.",15:"Llegamos a la misma posición que contra 2.Bf4."},
   plan:"Igual que contra 2.Bf4: ...Bb7, ...Qc7 y ...e5 o ...Ne4."},
  {id:"gd-colle", group:"sistemas", name:"Colle: 3.e3",
   moves:"d4 d5 Nf3 Nf6 e3 e6 Bd3 c5 c3 Nc6 Nbd2 Bd6 O-O O-O",
   notes:{4:"Sistema Colle: blancas preparan e4.",5:"Esquema del GDD.",7:"Golpeamos el centro antes de que blancas jueguen e4.",13:"Desarrollo completo."},
   plan:"...Qc7 y ...e5 si blancas no lo impiden, o ...b6 y ...Bb7. Si blancas juegan e4, cambiá en e4 o en d4 según convenga."}
 ]}
];
