const OPENINGS = [{ sub:"Repertorio con negras: Clásica 4...Bf5",
 id:"caro-kann", name:"Defensa Caro-Kann", short:"Caro-Kann", side:"b", first:"1.e4 c6",
 intro:"Contra 1.e4, las negras preparan ...d5 apoyado por el peón de c6. Es una defensa sólida: estructura de peones sana y, a diferencia de la Francesa, el alfil de casillas blancas sale antes de cerrar la cadena con ...e6.",
 groups:[
  {id:"clasica", name:"Clásica (3.Nc3 / 3.Nd2)", desc:"Blancas mantienen la tensión central y las negras cambian en e4 para sacar el alfil a f5."},
  {id:"avance", name:"Avance (3.e5)", desc:"Blancas ganan espacio. Las negras sacan el alfil fuera de la cadena y atacan la base con ...c5."},
  {id:"panov", name:"Panov-Botvinnik (4.c4)", desc:"Blancas aceptan un peón aislado en d4 a cambio de actividad."},
  {id:"cambio", name:"Cambio (4.Bd3)", desc:"Estructura simétrica. Blancas buscan un ataque de minorías invertido o presión en el flanco de rey."},
  {id:"otras", name:"Sistemas alternativos", desc:"Respuestas de blancas que evitan 2.d4."}
 ],
 lines:[
  {id:"cl-main", group:"clasica", name:"Principal: 6.h4 h6 7.Nf3",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 Nd7 h5 Bh7 Bd3 Bxd3 Qxd3 e6 Bd2 Ngf6 O-O-O Be7 Kb1 O-O",
   notes:{1:"La jugada que define la Caro-Kann: prepara ...d5 sin encerrar el alfil de c8.",3:"Golpe central. El peón de e4 queda atacado.",4:"Defiende e4 con pieza. Contra 3.Nd2 el plan es idéntico.",5:"Cambiamos en e4: soltamos el centro, pero ganamos tiempo y abrimos la diagonal del alfil.",7:"La Clásica. El alfil sale activo antes de ...e6 y ataca al caballo.",8:"El caballo se retira ganando tiempo sobre el alfil.",9:"Único buen retiro que mantiene el alfil en la diagonal b1-h7.",10:"Blancas amenazan h5 para atrapar el alfil.",11:"Casilla de escape en h7. No temas el peón en h6: más adelante sirve de refugio.",13:"El caballo de d7 controla e5 y evita Ne5, que presionaría g6/f7.",14:"Blancas ganan espacio en el flanco de rey, pero el peón de h5 puede volverse un blanco.",15:"El alfil se refugia. Sigue mirando la diagonal hacia b1.",17:"Cambiamos alfiles: menos piezas, menos ataque para blancas.",19:"Ahora sí ...e6: el alfil ya está fuera de la cadena.",21:"Desarrollo natural. f6 defiende h7 y controla e4.",22:"Enroque largo típico: blancas planean atacar con g4-g5 o jugar en el centro.",23:"Desarrollo modesto pero sólido. Mantiene opciones de enroque a ambos lados.",25:"Enroque corto. El plan es ...c5 o ...Qc7 y ...c5 para contraatacar en el centro."},
   plan:"Estructura: blancas tienen más espacio (d4, h5). Negras son sólidas y sin debilidades. Planes: ...c5 para atacar d4, ...Qc7/...Qa5 y, si blancas se enrocan largo, contraataque en el flanco de dama con ...b5 o ...c5. Ojo con la casilla e5: la controla el Nd7."},
  {id:"cl-nd2", group:"clasica", name:"Con 3.Nd2 (transpone)",
   moves:"e4 c6 d4 d5 Nd2 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 Nd7 h5 Bh7 Bd3 Bxd3 Qxd3 e6",
   notes:{4:"3.Nd2 evita la variante 3.Nc3 con ...b5 y otras. Para nosotros no cambia nada.",5:"Mismo cambio que contra 3.Nc3.",7:"Llegamos a la misma posición que la línea principal."},
   plan:"Misma estructura que la principal. Si conocés la Clásica con 3.Nc3, contra 3.Nd2 jugás exactamente igual."},
  {id:"cl-nf3", group:"clasica", name:"6.Nf3 sin h4",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 Nf3 Nd7 Bd3 Bxd3 Qxd3 e6 O-O Ngf6 c4 Be7",
   notes:{10:"Sin h4, el alfil de g6 no está en peligro. Blancas juegan un desarrollo tranquilo.",11:"El mismo esquema: controlamos e5.",13:"Cambiamos el alfil de todas formas: el de d3 apuntaba a nuestro enroque.",19:"Enroque corto después, y el plan típico es ...c5 o ...Qc7 con ...e5."},
   plan:"Posición tranquila. Negras completan desarrollo con ...O-O, ...Qc7 y buscan liberar con ...c5 o ...e5. Sin h5 blanco, el peón de h7 no hace falta mover."},
  {id:"cl-bc4", group:"clasica", name:"6.Bc4",
   moves:"e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 Bc4 e6 N1e2 Nf6 h4 h6 Nf4 Bh7 O-O Bd6",
   notes:{10:"El alfil presiona e6 y f7.",11:"Cerramos la diagonal hacia f7. Con el alfil de c8 afuera, ...e6 no tiene costo.",12:"El caballo va a f4 para saltar sobre g6.",14:"De nuevo h4-h5 como amenaza al alfil.",15:"Preparamos el retiro a h7.",17:"El alfil se aparta del caballo de f4.",19:"Desarrollo activo: el alfil de d6 discute el caballo de f4."},
   plan:"Negras se desarrollan con ...Nbd7, ...Qc7 y enroque. El cambio en f4 (...Bxf4) es habitual para quitar el caballo más peligroso."},
  {id:"av-short", group:"avance", name:"Short: 4.Nf3 e6 5.Be2",
   moves:"e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 c5 Be3 Nd7 O-O Ne7 c3 Nc6 Nbd2 Be7",
   notes:{4:"3.e5: blancas ganan espacio y cierran el centro.",5:"El alfil sale ANTES de ...e6. Esta es la ventaja sobre la Francesa.",7:"Ahora sí cerramos con ...e6.",9:"Atacamos la base de la cadena (d4). Es el plan central de las negras en el Avance.",11:"El caballo de d7 presiona e5 y apoya ...c5.",13:"Ruta Ne7-c6 para sumar presión sobre d4.",15:"Tercera pieza apuntando a d4.",17:"Desarrollo y luego enroque corto."},
   plan:"Presión sobre d4 con ...c5, ...Nc6, ...Qb6. Blancas intentan mantener el centro. Si blancas cambian en c5, recuperamos con el alfil o el caballo con buen juego. Evitá abrir el flanco de rey innecesariamente."},
  {id:"av-h4", group:"avance", name:"Tal: 4.h4",
   moves:"e4 c6 d4 d5 e5 Bf5 h4 h5 Bd3 Bxd3 Qxd3 e6 Bg5 Qa5+ c3 Qa6 Qxa6 Nxa6",
   notes:{6:"Blancas amenazan g4 atrapando el alfil.",7:"Frenamos el avance del peón de h. La casilla g5 queda débil, pero g4 deja de ser posible.",9:"Cambiamos: el alfil de d3 era el mejor de blancas.",13:"Truco típico: jaque que obliga a c3 y prepara el cambio de damas.",15:"Ofrecemos cambiar damas: sin damas, la ventaja de espacio blanca pesa menos.",17:"El caballo en a6 va a c7 o b4 si hace falta."},
   plan:"Final cómodo para negras: ...c5 para atacar el centro, ...Nc7 y ...Ne7-f5. La debilidad de g5/h4 de blancas compensa la de g6/h5."},
  {id:"av-nc3", group:"avance", name:"4.Nc3 e6 5.g4",
   moves:"e4 c6 d4 d5 e5 Bf5 Nc3 e6 g4 Bg6 Nge2 c5 h4 h5 Nf4 Bh7",
   notes:{8:"Variante agresiva: blancas corren con peones contra el alfil.",9:"El alfil se retira sin perder la diagonal.",11:"Contraataque central inmediato: es la respuesta correcta a los avances en el flanco.",13:"Frenamos h5, que atraparía el alfil.",15:"El alfil queda en h7. Posición muy teórica: más adelante vale la pena revisarla con motor."},
   plan:"Línea filosa. Negras deben contraatacar rápido con ...Nc6, ...cxd4 y ...Nge7. No te quedes pasivo: si blancas completan g4-h4-Nf4 sin respuesta central, el ataque es peligroso."},
  {id:"av-bd3", group:"avance", name:"4.Bd3",
   moves:"e4 c6 d4 d5 e5 Bf5 Bd3 Bxd3 Qxd3 e6 Nf3 Qb6 O-O c5",
   notes:{6:"Blancas ofrecen cambiar su mejor alfil. Es inofensivo.",7:"Cambiamos con gusto: nuestro alfil malo por su alfil bueno.",11:"La dama presiona d4 y b2.",13:"Golpe estándar contra la cadena."},
   plan:"Negras están muy cómodas: sin alfiles de casillas blancas, la estructura de la Francesa sin su problema principal. Plan: ...Nc6, ...cxd4, ...Nge7-f5."},
  {id:"pn-main", group:"panov", name:"Principal: 5...e6",
   moves:"e4 c6 d4 d5 exd5 cxd5 c4 Nf6 Nc3 e6 Nf3 Be7 cxd5 Nxd5 Bd3 Nc6 O-O O-O Re1 Bf6 Be4 Nce7",
   notes:{4:"Cambio en d5.",5:"Retomamos con el peón de c.",6:"Panov: blancas atacan d5 y aceptan peón aislado en d4.",7:"Presionamos d5 y desarrollamos.",9:"Estructura sólida: vamos a bloquear el peón aislado.",11:"Desarrollo antes de enrocar.",13:"El caballo en d5 es el bloqueador ideal del peón aislado.",15:"Presión sobre d4.",19:"El alfil presiona d4 desde f6.",21:"Reforzamos d5: el caballo de e7 apoya al de d5."},
   plan:"Juego contra el peón aislado: bloquear en d5, cambiar piezas menores y presionar d4. Cada cambio favorece a negras. Blancas buscan ataque con Ne5, Bc2 y Qd3 contra h7."},
  {id:"cm-main", group:"cambio", name:"Principal: 4.Bd3",
   moves:"e4 c6 d4 d5 exd5 cxd5 Bd3 Nc6 c3 Nf6 Bf4 Bg4 Qb3 Qd7 Nd2 e6 Ngf3 Bd6 Bxd6 Qxd6 O-O O-O",
   notes:{6:"Variante del Cambio: blancas se desarrollan sin tensión.",7:"Presión sobre d4.",11:"El alfil sale activo antes de ...e6.",12:"Blancas atacan b7.",13:"Defendemos b7 y conectamos.",15:"Cerramos la cadena ahora que el alfil ya salió.",17:"Ofrecemos cambio de alfiles.",21:"Posición equilibrada."},
   plan:"Ataque de minorías: ...b5-b4 para crear una debilidad en c3. Blancas juegan en el flanco de rey con Ne5 y f4. Estructura muy segura para negras."},
  {id:"ot-2n", group:"otras", name:"Dos Caballos: 2.Nc3 d5 3.Nf3",
   moves:"e4 c6 Nc3 d5 Nf3 Bg4 h3 Bxf3 Qxf3 e6 d3 Nf6 Bd2 Nbd7 g4 Bb4",
   notes:{2:"Blancas evitan 2.d4.",3:"Igual que siempre: ...d5.",5:"Clavada: el alfil sale y presiona el caballo que defiende e4.",7:"Cedemos la pareja de alfiles a cambio de estructura y desarrollo.",9:"Sólido: e6 y d5 frenan a la dama y al alfil.",15:"Clavamos el caballo de c3 y presionamos e4."},
   plan:"Negras juegan ...d4 o ...dxe4 según convenga, ...Qc7 y enroque. Blancas tienen la pareja de alfiles pero sin centro."},
  {id:"ot-fant", group:"otras", name:"Fantasía: 3.f3",
   moves:"e4 c6 d4 d5 f3 e6 Nc3 Bb4 Bd2 Ne7 a3 Bxc3 Bxc3 b6",
   notes:{4:"Blancas sostienen e4 con peón.",5:"Sólido: preparamos ...c5 o ...dxe4 según convenga.",7:"Clavada sobre el caballo que defiende e4.",9:"El caballo va a g6 o f5, nunca a f6 (lo molestaría e5).",11:"Cambiamos: blancas pierden un defensor de e4.",13:"Preparamos ...Ba6 para cambiar el alfil de casillas blancas."},
   plan:"Presión sobre e4 y el centro con ...dxe4 o ...c5. El peón de f3 debilita el flanco de rey blanco y la diagonal g1-a7."},
  {id:"ot-c4", group:"otras", name:"2.c4",
   moves:"e4 c6 c4 d5 exd5 cxd5 cxd5 Nf6 Nc3 Nxd5 Nf3 Nc6 Bb5 e6 O-O Be7 d4 O-O",
   notes:{2:"Blancas atacan d5 antes de que se arme.",3:"Igual jugamos ...d5.",7:"No retomamos con la dama: ...Nf6 recupera el peón con desarrollo.",9:"Peón recuperado.",11:"Presión sobre d4.",17:"Suele transponer a estructuras de la Panov."},
   plan:"Estructura de peón aislado blanco, como en la Panov. Mismo plan: bloquear en d5 y presionar d4."},
  {id:"ot-kia", group:"otras", name:"Indio de Rey: 2.d3",
   moves:"e4 c6 d3 d5 Nd2 e5 Ngf3 Bd6 g3 Nf6 Bg2 O-O O-O Re8",
   notes:{2:"Sistema cerrado. Blancas evitan teoría.",5:"Tomamos el centro con los dos peones.",7:"El alfil apoya e5.",13:"La torre refuerza e5."},
   plan:"Negras tienen un centro amplio. Planes: ...a5-a4 para ganar espacio en el flanco de dama, ...Nbd7 y ...Bc7. Blancas buscan f4 o c3-d4."},
  {id:"ot-bc4", group:"otras", name:"2.Bc4",
   moves:"e4 c6 Bc4 d5 exd5 cxd5 Bb5+ Bd7 Bxd7+ Nxd7 d4 Ngf6",
   notes:{2:"Blancas desarrollan el alfil donde ...d5 lo ataca.",3:"Directamente ...d5 con tiempo.",7:"Cubrimos el jaque ofreciendo cambio.",9:"Retomamos con desarrollo.",11:"Negras están cómodas: buen centro y desarrollo fácil."},
   plan:"Posición cómoda: ...e6, ...Bd6 y enroque. Negras no tienen problemas."}
 ]},
{id:"viena", name:"Viena", side:"w", first:"1.e4 e5 2.Nc3", sub:"Repertorio con blancas: gambito 3.f4 y 3.Bc4",
 intro:"Con 2.Nc3 las blancas controlan d5 y preparan f4 sin exponer el rey de entrada. Contra 2...Nf6 jugamos el gambito 3.f4; contra 2...Nc6, el alfil a c4 con la idea Qg4 si negras juegan ...Bc5.",
 groups:[
  {id:"gambito", name:"Gambito de Viena (2...Nf6 3.f4)", desc:"Abrimos la columna f para atacar. Negras eligen entre el contragolpe ...d5, aceptar o jugar sólido."},
  {id:"bc4", name:"3.Bc4 contra 2...Nc6", desc:"El alfil apunta a f7. Contra ...Bc5 aparece la jugada 4.Qg4, con amenazas dobles."},
  {id:"otras", name:"Otras segundas de negras", desc:"Para que no te saquen de la preparación en la jugada 2."}
 ],
 lines:[
  {id:"vg-d5", group:"gambito", name:"3...d5 (principal)",
   moves:"e4 e5 Nc3 Nf6 f4 d5 fxe5 Nxe4 Nf3 Be7 d4 O-O Bd3 f5 exf6 Bxf6 O-O Nc6",
   notes:{2:"2.Nc3: controla d5 y deja libre el peón de f para avanzar.",4:"El gambito: atacamos e5 y abrimos la columna f.",5:"La respuesta más fuerte: contragolpe central.",6:"Ganamos espacio con tiempo sobre el caballo de f6.",8:"Desarrollo natural. El peón de e5 queda defendido.",10:"Centro de peones sólido.",12:"El alfil apunta al enroque y presiona el caballo de e4.",14:"Cambiamos para abrir la columna f contra el rey negro.",16:"Enroque con la torre ya en la columna semiabierta."},
   plan:"Blancas tienen presión en la columna f y buen centro. Planes: Ne2/Nxe4 para eliminar el caballo central, Qe1-h4 o Qe2, Bf4/Bg5 y torres en la columna f."},
  {id:"vg-exf4", group:"gambito", name:"3...exf4 (acepta)",
   moves:"e4 e5 Nc3 Nf6 f4 exf4 e5 Ng8 Nf3 d6 d4 dxe5 Qe2 Be7 dxe5",
   notes:{5:"Negras aceptan el peón.",6:"Clave: echamos el caballo antes de que juegue ...d5.",7:"El único retiro seguro.",8:"Evita ...Qh4+ y desarrolla.",10:"Centro fuerte. El peón de f4 lo vamos a recuperar con Bxf4.",12:"La dama defiende e5 por la columna e y prepara Bxf4 y enroque largo.",14:"Retomamos y mantenemos el peón central."},
   plan:"Blancas recuperan el peón con Bxf4, enrocan largo y juegan con ventaja de desarrollo y espacio. El peón de e5 es una cuña en la posición negra."},
  {id:"vg-exf4-qe7", group:"gambito", name:"3...exf4 4.e5 Qe7",
   moves:"e4 e5 Nc3 Nf6 f4 exf4 e5 Qe7 Qe2 Ng8 Nf3 d6 exd6 Qxe2+ Bxe2 cxd6 Nd5",
   notes:{7:"Clavada sobre e5: la dama negra ataca el peón.",8:"Defendemos e5 con la dama y rompemos la clavada.",12:"Cambiamos y abrimos el juego.",14:"Retomamos con el alfil: desarrollo con tiempo.",16:"El caballo salta a d5 atacando c7 y f4."},
   plan:"Final cómodo para blancas: recuperamos el peón de f4 y tenemos más actividad. Nd5, Bxf4 y enroque."},
  {id:"vg-d6", group:"gambito", name:"3...d6 (sólido)",
   moves:"e4 e5 Nc3 Nf6 f4 d6 Nf3 Nc6 Bb5 Bd7 O-O",
   notes:{5:"Negras sostienen e5 sin tomar riesgos.",6:"Desarrollo con presión sobre e5.",8:"Clavada sobre el caballo que defiende e5.",10:"Enroque. Amenaza fxe5 abriendo la columna f."},
   plan:"Blancas buscan d3, Qe1-g3 o Kh1 y fxe5 en el momento justo. La columna f es la vía de ataque."},
  {id:"vg-nc6", group:"gambito", name:"3...Nc6",
   moves:"e4 e5 Nc3 Nf6 f4 Nc6 fxe5 Nxe5 d4 Ng6 e5 Ng8 Nf3",
   notes:{5:"Negras desarrollan y dejan que blancas tomen en e5.",6:"Tomamos: el caballo negro queda expuesto.",8:"Echamos el caballo con tiempo.",10:"Seguimos ganando tiempos.",12:"Centro enorme y desarrollo muy superior."},
   plan:"Ventaja clara de espacio. Bd3 o Bc4, enroque y ataque en el flanco de rey."},
  {id:"bc-bc5", group:"bc4", name:"3...Bc5 4.Qg4",
   moves:"e4 e5 Nc3 Nc6 Bc4 Bc5 Qg4 Qf6 Nd5 Qxf2+ Kd1 Kf8 Nh3 Qd4 d3",
   notes:{4:"El alfil apunta a f7.",5:"Negras copian el esquema.",6:"Ataca g7. Si negras no lo cubren bien, Qxg7 gana la torre de h8. Además la dama y el alfil apuntan juntos a f7.",7:"La defensa más natural: protege g7 y amenaza f2.",8:"Atacamos la dama y c7.",9:"Negras toman con jaque, pero la dama queda lejos de su rey.",10:"El rey se mueve. Parece arriesgado pero la dama negra va a quedar sola.",12:"Defendemos y preparamos Rf1 contra f7.",14:"Encerramos el juego de la dama negra y preparamos Rf1."},
   plan:"Negras ganaron un peón pero su rey no se puede enrocar y la dama está expuesta. Blancas siguen con Rf1, Qxg7 si se permite y c3 para echar la dama."},
  {id:"bc-bc5-g6", group:"bc4", name:"3...Bc5 4.Qg4 g6",
   moves:"e4 e5 Nc3 Nc6 Bc4 Bc5 Qg4 g6 Qf3 Nf6 Nge2 d6 d3",
   notes:{7:"Negras defienden g7 con peón, pero debilitan f6 y h6.",8:"La dama vuelve a presionar f7.",9:"Tapa la diagonal hacia f7.",10:"Desarrollo sin bloquear el peón de f.",12:"Esquema sólido: preparamos Bg5 y f4."},
   plan:"Las casillas oscuras del flanco de rey negro quedaron debilitadas. Blancas juegan Bg5, h4-h5 o f4 según la posición."},
  {id:"bc-nf6", group:"bc4", name:"3...Nf6",
   moves:"e4 e5 Nc3 Nc6 Bc4 Nf6 d3 Bc5 f4 d6 Nf3",
   notes:{5:"Negras desarrollan y amenazan ...Nxe4.",6:"Defendemos e4 con peón. Preparamos f4.",8:"Ahora sí f4: estructura de gambito del rey rehusado con el alfil en c4.",10:"Desarrollo. Si negras cambian en f4, Bxf4 con juego activo."},
   plan:"Blancas enrocan corto y juegan con la columna f. Ojo con ...Ng4 contra f2: el enroque lo neutraliza. Si negras juegan ...Na5, retirar el alfil a b3."},
  {id:"ot-bc5", group:"otras", name:"2...Bc5",
   moves:"e4 e5 Nc3 Bc5 Nf3 d6 d4 exd4 Nxd4 Nf6 Bg5",
   notes:{3:"Negras sacan el alfil antes que los caballos.",4:"Desarrollo con ataque a e5.",6:"Golpe central con tiempo sobre el alfil.",8:"Centralizamos el caballo.",10:"Clavada sobre f6: presión y desarrollo."},
   plan:"Blancas tienen más centro. Qd2 y enroque largo es un plan agresivo; también Be2 y enroque corto."},
  {id:"ot-d6", group:"otras", name:"2...d6",
   moves:"e4 e5 Nc3 d6 Nf3 Nf6 d4 Nbd7 Bc4 Be7 O-O O-O",
   notes:{3:"Negras juegan pasivo.",4:"Desarrollo con presión a e5.",6:"Transpone a una Philidor favorable para blancas.",8:"El alfil en c4 presiona f7.",10:"Enroque y a desarrollar el juego central."},
   plan:"Ventaja de espacio. Planes: a4 para frenar ...b5, Re1, h3 y Be3. Negras están sólidas pero apretadas."}
 ]},
{id:"holandesa", name:"Holandesa Leningrado", short:"Holandesa", cover:8, side:"b", first:"1...f5 contra 1.d4, 1.c4, 1.Nf3 y 1.g3", sub:"Repertorio con negras: Leningrado",
 intro:"Con 1...f5 las negras controlan e4 y buscan juego de ataque en el flanco de rey. En la Leningrado el alfil va a g7, como en la India de Rey, y el plan típico es ...d6, ...Qe8 y ...e5.",
 groups:[
  {id:"principal", name:"Principal (1.d4 f5 2.g3)", desc:"El esquema fiancheto de blancas. Es la posición central del repertorio."},
  {id:"transp", name:"Otras primeras jugadas", desc:"1.c4, 1.Nf3 y 1.g3 llegan a la misma estructura."},
  {id:"anti", name:"Anti-Holandesas", desc:"Blancas evitan la estructura con jugadas tempranas contra f5."}
 ],
 lines:[
  {id:"ln-main", group:"principal", name:"Principal con 7.Nc3 Qe8",
   moves:"d4 f5 g3 Nf6 Bg2 g6 Nf3 Bg7 O-O O-O c4 d6 Nc3 Qe8 d5 a5 Nd4 Na6 e4 fxe4 Nxe4 Nxe4 Bxe4 Nc5",
   notes:{1:"1...f5: controlamos e4 y desequilibramos desde la primera jugada.",3:"Desarrollo y control de e4.",5:"Fiancheto: el alfil de g7 va a ser la pieza clave de la defensa.",7:"El alfil cubre el rey y presiona la gran diagonal.",9:"Enroque rápido. En la Holandesa el rey negro necesita estar seguro antes de abrir.",11:"Controlamos e5 y preparamos ...e5.",13:"La jugada típica de la Leningrado: la dama va a h5 o f7 y apoya ...e5.",15:"Ganamos espacio en el flanco de dama y aseguramos c5 para un caballo.",17:"El caballo va a c5 por a6.",19:"Abrimos la columna f para las torres.",21:"Simplificamos el centro.",23:"El caballo llega a c5, casilla fuerte asegurada por ...a5."},
   plan:"Negras tienen juego en las casillas oscuras (c5, e5) y en la columna f. Planes: ...Bd7, ...Qf7 presionando c4 y f2, ...c6 para abrir el flanco de dama. El alfil de g7 no se cambia."},
  {id:"ln-c4", group:"principal", name:"Con 2.c4",
   moves:"d4 f5 c4 Nf6 Nc3 g6 Nf3 Bg7 g3 O-O Bg2 d6 O-O Qe8",
   notes:{3:"El mismo esquema, sin importar el orden de blancas.",9:"Enroque antes de ...d6.",13:"Llegamos a la posición principal."},
   plan:"Transpone a la línea principal. Seguí el mismo plan: ...a5, ...Na6 y ...e5 o ...c6."},
  {id:"tr-c4", group:"transp", name:"1.c4 f5",
   moves:"c4 f5 g3 Nf6 Bg2 g6 Nc3 Bg7 Nf3 O-O O-O d6 d4 Qe8",
   notes:{1:"Contra la Inglesa también jugamos 1...f5.",3:"Mismo esquema.",11:"Si blancas no juegan d4, igual seguimos con ...Qe8 y ...e5.",13:"Transpone a la principal."},
   plan:"Si blancas mantienen el peón en d3 en lugar de d4, el plan ...e5 es todavía más fuerte porque tenemos más centro."},
  {id:"tr-nf3", group:"transp", name:"1.Nf3 f5",
   moves:"Nf3 f5 g3 Nf6 Bg2 g6 O-O Bg7 c4 O-O Nc3 d6 d4 Qe8",
   notes:{1:"Contra 1.Nf3 el mismo movimiento.",3:"Nada cambia.",13:"Transpone de nuevo a la principal."},
   plan:"Misma estructura que la principal. Si blancas juegan d3 y e4, respondemos con ...e5 y ...Nc6."},
  {id:"tr-g3", group:"transp", name:"1.g3 f5",
   moves:"g3 f5 Bg2 Nf6 Nf3 g6 O-O Bg7 c4 O-O d4 d6 Nc3 Qe8",
   notes:{1:"Contra 1.g3, mismo esquema.",13:"Transpone a la principal."},
   plan:"Mismo plan que la principal."},
  {id:"an-staunton", group:"anti", name:"Gambito Staunton 2.e4",
   moves:"d4 f5 e4 fxe4 Nc3 Nf6 Bg5 g6 f3 exf3 Nxf3 Bg7 Bd3 O-O O-O d6",
   notes:{2:"Blancas ofrecen un peón para abrir el juego.",3:"Aceptamos: si no, blancas toman en f5 con buen juego.",5:"Defendemos el peón de e4.",7:"Mantenemos el esquema Leningrado.",9:"Tomamos otro peón. El caballo de f3 pierde tiempo.",11:"El alfil defiende el enroque.",13:"Rey seguro antes de todo.",15:"Controlamos e5 y consolidamos el peón de ventaja."},
   plan:"Negras tienen un peón de ventaja. Blancas buscan ataque con Qe1-h4 y Bh6. Plan negro: ...Nc6, ...Bg4 y cambiar piezas para capitalizar el peón."},
  {id:"an-staunton-f3", group:"anti", name:"Staunton con 4.f3",
   moves:"d4 f5 e4 fxe4 Nc3 Nf6 f3 exf3 Nxf3 g6 Bd3 Bg7 O-O O-O",
   notes:{6:"Blancas buscan abrir la columna f de inmediato.",7:"Tomamos y quedamos con peón de ventaja.",9:"Seguimos con el esquema.",13:"Rey seguro."},
   plan:"Igual que el Staunton con Bg5: consolidar con ...d6, ...Nc6 y ...Bg4."},
  {id:"an-bg5", group:"anti", name:"2.Bg5",
   moves:"d4 f5 Bg5 h6 Bh4 g5 Bg3 Nf6 e3 d6 h4 g4",
   notes:{2:"Blancas atacan e7 y amenazan cambiar el caballo antes de que salga.",3:"Preguntamos al alfil.",5:"Lo echamos del flanco de rey.",7:"Recién ahora el caballo.",9:"Controlamos e5.",11:"Cerramos el flanco: el alfil de g3 queda con poco juego."},
   plan:"Negras ganaron espacio en el flanco de rey. Planes: ...Bg7, ...Nc6 y ...e5. Cuidado con la casilla e6 y la diagonal h5-e8."},
  {id:"an-nc3", group:"anti", name:"2.Nc3",
   moves:"d4 f5 Nc3 Nf6 Bg5 d5 Bxf6 exf6 e3 c6 Bd3 g6 Nge2 Bd6",
   notes:{2:"Blancas preparan e4.",5:"Frenamos e4 con peón.",7:"Retomamos hacia el centro: la columna e queda abierta.",9:"Cadena sólida.",11:"Fiancheto no hace falta: el alfil va a d6.",13:"El alfil controla e5 y f4."},
   plan:"Estructura tipo Stonewall con la pareja de alfiles para negras. Plan: ...O-O, ...Nd7-f8, ...Qc7. El peón de e5 es una ruptura para blancas a vigilar."}
 ]}
];
